### DISCUSSION TITLE
Run a console script without typing "pdm run"

### DISCUSSION THREAD

**Discussion by tanng1999** [pdm-project/pdm#1236] [Q&A]
I have a CLI using Click with Setuptools where I can run a console script by its own name.  Here is an example, 

https://click.palletsprojects.com/en/8.0.x/setuptools/

Is there a way to have PDM-enabled project to run a console script by its own name, i.e. without always prefix "pdm run"?  Thanks.

**Comment by Hnasar** [comment]
@tanng1999 if you use PDM to install into a virtual env, and then you activate the virtual env you will be able to run the script by its own name.

**Comment by floatingpurr** [comment]
Same question but I'm not sure I understood @Hnasar's hint. In Poetry you just write in your `pyproject.toml`:

```toml
[tool.poetry.scripts]
mycli = "mycli.__main__:main"
```

and you have the command `mycli` available in the virtualenv. How can I do the same with pdm?

**Reply by pawamoy** [reply]
```toml
[project.scripts]
mycli = "mycli.__main__:main"
```
