### DISCUSSION TITLE
How can I reference other optional-dependencies in an optional-dependency?

### DISCUSSION THREAD

**Discussion by FossenWang** [pdm-project/pdm#1241] [Q&A]
If an optional-dependency actually rely on some other optional-dependencies, I hope to only reference other groups of dependency, rather than write the whole dependencies again.
For example:
```
[project]
name = "this-package"

[project.optional-dependencies]
flask = ["flask"]
sql = ["sqlalchemy", "pymysql"]
flask-sql = ["flask-sqlalchemy", "this-package[flask,sql]"]
```

I've tried this with `setup.py` and `pip install` which works.

**Comment by inigohidalgo** [comment]
Hey @FossenWang , not sure if this is a new feature, but you should be able to do that according to docs: https://pdm.fming.dev/latest/usage/dependency/#add-dependencies

```toml
[project]
name = "foo"
version = "0.1.0"

[project.optional-dependencies]
socks = ["pysocks"]
jwt = ["pyjwt"]
all = ["foo[socks,jwt]"]
```
