### DISCUSSION TITLE
Publish to testpypi

### DISCUSSION THREAD

**Discussion by coccoinomane** [pdm-project/pdm#1443] [Show and tell]
Hello builders!

I always publish my packages to test.pypi.org first, because I am a bit of a paranoid. So I came up with this script in pyproject.toml:

```toml
[tool.pdm.scripts]
publish_test = "pdm publish -r testpypi -u ${PDM_PUBLISH_TEST_USERNAME} -P ${PDM_PUBLISH_TEST_PASSWORD}"
```

To make it work, you have to export `PDM_PUBLISH_TEST_USERNAME` and `PDM_PUBLISH_TEST_PASSWORD` in your shell. If you use bash, then you just need to edit `.bash_profile`.

Hope it helps all other paranoids out there ;-)

Cheers,
Cocco
