### DISCUSSION TITLE
Why can't I install a default dependency in editable mode?

### DISCUSSION THREAD

**Discussion by cheog** [pdm-project/pdm#1479] [Q&A] [answered]
# Question
PDM has the behavior "Editable installs are only allowed in the dev dependency group. Other groups, including the default, will fail with a [PdmUsageError]." (by the way, love your documentation, it makes me so happy that this piece of behavior is documented). Why is it this way? Is there a potential future where you can allow this or is there some way to solve the problem  below for monorepos?

# Why I want this
I have a monorepo system going on that looks something like
```
/
|- core_package
   |- pyproject.toml
   |- src
   |- test
   ...
|- service
   |- pyproject.toml (depends on core_package)
   |- src
   |- test
   ...
```

I'd like to be able install core_package as an editable dependency so my editor picks up on all the changes going on and autocompletes properly and so when I run linting all that works without re-locking/installing.

**Comment by frostming** [comment, marked as answer]
Just duplicate the requirement in dev-dependencies:

```toml
[project]
dependencies = ["core_package==1.0"]  # the versioned requirement

[tool.pdm.dev-dependencies]
dev = [
    "-e file:///${PROJECT_ROOT}/../core_package#egg=core_package"
]
```
