### DISCUSSION TITLE
Confused with version resolution rule

### DISCUSSION THREAD

**Discussion by madjxatw** [pdm-project/pdm#1754] [General]
I am using python 3.11 on my machine and I have the following constraints in `pyproject.toml`:

```toml
dependencies = [
    "numpy>=1.18.5"
]
require-python = ">3.7"
```

`pdm install` finally picks numpy 1.21.1 zip file and compiles the source.  So

- Why does it choose a source package but not a pre-built wheel?  
- In order to support python 3.7, why does it pick 1.21.1 over 1.21.6. Version 1.21.6 is the latest one that supports py37, shouldn't it choose the latest workable one?

Another similar example:

```toml
dependencies = [
    "pandas>=1.1.4"
]
require-python = ">3.7"
```

`pdm install` picks `pandas.1.1.5.tar.gz` and compiles the source. Why doesn't it choose pandas 1.2.0 which also supports python 3.7 ~ 3.9.
