### DISCUSSION TITLE
Encountering exception when using internal artifactory pypi repo

### DISCUSSION THREAD

**Discussion by racc** [pdm-project/pdm#1757] [Q&A] [answered]
Hi all, 

I'm encountering a potential issue when trying to connect to a company internal artifactory pypi repo which requires authentication.

The exception encountered is:
pdm.exceptions.PdmException: The credentials for artifactory.example.com are not provided. Please rerun the command with `-v` option.

Contents of `~/.config/pdm/config.toml`
``` toml
[pypi]
url = "https://<username>:<password>@artifactory.example.com/artifactory/api/pypi/pypi-remote/simple"
verify_ssl = false

[pypi.extra]
url = "https://<username>:<password>@artifactory.example.com/artifactory/api/pypi/pypi-extra/simple"
verify_ssl = false
```
PDM version:
  2.4.7
Python Interpreter:
  /opt/rh/rh-python38/root/usr/bin/python (3.8)

When I run `pdm install -v` and enter credentials and save them to the keyring the build succeeds, however I would like to run this in non-interactive mode and would expect that PDM should be able to work in this way.

I have also tried adding `username` and `password` fields to the `config.toml` file but this results in:
401 Error Credentials not correct.

Is this a potential bug, or am I doing something wrong here?

Thanks in advance,
Jason

**Comment by frostming** [comment]
Try a different config pattern:

```toml
[pypi]
url = "https://artifactory.example.com/artifactory/api/pypi/pypi-remote/simple"
verify_ssl = false
username = "<username>"
password = "<password>"
```
