### DISCUSSION TITLE
How to configure PDM repositories in CI/CD when no password is required?

### DISCUSSION THREAD

**Discussion by baggiponte** [pdm-project/pdm#1790] [Q&A] [answered]
Some private repository services like [GemFury](gemfury.com) only provide _username_ upload tokens no password, like this: `https://<TOKEN>:@service.pypi.com/simple`. 

Working with such services is hard, because you cannot/are not supposed to set an empty value with `pdm config repository.private.password`.

The hack I found is to manually configure pdm settings for the repo like this:

```toml
[pypi.private]
url = "<SERVICE_URL>"
username = "<SERVICE_TOKEN>"
password = ""
```

However this does not work in CI/CD, e.g. with GitHub Actions you cannot set an empty secret. I tried setting `password = "__token__"` but of course that does not work.

Is there a temporary workaround for this? Thanks!
