### DISCUSSION TITLE
Override git dependency only if fetching/resolution failed

### DISCUSSION THREAD

**Discussion by pawamoy** [pdm-project/pdm#1857] [Q&A]
I'm trying to do the following thing:

- in my project, depend on a package specified with `git+ssh://git@github.com/...`, or `git+https://${TOKEN}@github.com/...`
- if it fails (user does not have ssh access, or TOKEN is empty/invalid), fallback on PyPI package

Example:

```toml
[tool.pdm.dev-dependencies]
docs = [
    "mkdocs-material @ git+ssh://git@github.com/squidfunk/mkdocs-material-insiders.git",
]

[tool.pdm.resolution.overrides]
mkdocs-material = ">=9"
```

But overrides always take precedence. I'd like PDM to try to fetch/resolve the specified dependency, and only fallback on overrides if it fails. I'd also like to disable Git credentials prompting for contributors.

The goal is to allow myself to use the private version, while still allowing contributors to install dependencies and build docs using the public version of mkdocs-material.

Would you be open to such a change/feature? Are there alternatives (I couldn't find any)?
