### DISCUSSION TITLE
automatically install pre-commit hooks (post-install-commands)

### DISCUSSION THREAD

**Discussion by juftin** [pdm-project/pdm#2412] [Ideas]
I've been exploring moving from hatch to PDM and one feature I'm finding myself missing is [post-install-commands](https://hatch.pypa.io/latest/config/environment/overview/#post-install). In particular, I was using this feature to automatically install pre-commit hooks when the project is first installed:

```toml
[tool.hatch.envs.default]
post-install-commands = [
  "pre-commit install"
]
```

I think something similar would be a great feature for PDM

**Comment by juftin** [comment]
Actually, this is already enabled by [hook-scripts](https://pdm-project.org/latest/usage/scripts/#hook-scripts) 🤦 

```toml
[tool.pdm.scripts]
post_install = "pre-commit install"
```
