### DISCUSSION TITLE
Informations about automatic tags using CI/CD

### DISCUSSION THREAD

**Discussion by JeyDi** [pdm-project/pdm#2501] [Q&A]
Hi all!

I am trying to make a python package with my CI/CD and publish it on Gitlab (same thing as on Github).

Is there any way to dynamically and automatically assign the git tag to the version of my python package? Without having to edit by hand every time the pyproject.toml with version = "<myversion>"?
Have you ever tried this or do you have any examples?

Thank you!

**Comment by frostming** [comment]
It depends on which build backend you are using. For pdm-backend: https://backend.pdm-project.org/metadata/#read-from-scm-tag-supporting-git-and-hg

**Comment by JeyDi** [comment]
Thanks @frostming I solved the problem and found a solution, I'll write here so maybe can help someone else:

If you need to have automatic versioning on git using tags for your python package in general you can:

1. add `dynamic = ["version"]` instead of: `version = "v0.0.2"` inside the `pyproject.toml` file
2. specify to use the `pdm.backend` to make the build inside the `pyproject.toml` file:
    
    ```toml
    [build-system]
    requires = ["pdm-backend"]
    build-backend = "pdm.backend"
    ```
    
3. specify the type of versioning you want to use inside the `pyproject.toml`

```toml
[tool.pdm.version]
source = "scm"
# source = "file"
# path = "[version.py](http://version.py/)"
# write_to = "version.txt"
# write_template = "**version** = '{}'"
```

4. Configure the gitlab pipeline using this script instructions

```yaml
- mkdir pypackages && pdm install --prod --no-lock --no-editable
- export PDM_BUILD_SCM_VERSION=${CI_COMMIT_TAG}
- pdm build
- pdm publish --repository "[https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi](https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi)" --username ${REGISTRY_TOKEN_NAME} --password ${REGISTRY_TOKEN_KEY}
```

It’s really important to specify the environment variable used by PDM:  `PDM_BUILD_SCM_VERSION` with the tag of the pipeline.

I think we can create a tutorial in the documentation page to summarise also this example, what do you think?
