### DISCUSSION TITLE
How do I specify binary and library project in one go?

### DISCUSSION THREAD

**Discussion by wizpresso-steve-cy-fan** [pdm-project/pdm#2626] [Q&A]
I want to do it just like Rust, where we can have a `src/lib.rs` and a `src/main.rs`, that separates the public content installable by the others (such as RPC API definition) and the private content NOT installable by the others and should be excluded (such as the implemented RPC server). Is it possible to do this in PDM? Of course maybe I can split this into multiple pyprojects, but it will be very tedious to do so (for example, I have to add another `generated-api` entry for monorepo setup)

**Comment by pawamoy** [comment]
With the following layout:

```
./
    src/
        public/
            __init__.py
        private/
            __init__.py
```

You can instruct PDM to only include the `public` folder in built distributions:

```toml
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.build]
package-dir = "src"
includes = ["src/public"]
```

Could you try that and let us know if that works for you?
