### DISCUSSION TITLE
Only install dev-dependencies group package (without prod)

### DISCUSSION THREAD

**Discussion by bitfoo1** [pdm-project/pdm#2634] [Q&A]
Hi, 
again thank you for this awesome piece of software. 
Now to my question, is it possible to install only a `dev-dependencies` dependency without installing `prod` dependencies. 

Example use case:

I have two packages **A** and **B**. 
**A** has some dependencies but nothing special
**B** has **A** as a dependency and other packages.

I want to use both packages in on project (git). **A** is my infrastructure package and **B** my pipeline package.
Because  **A** is a dependency of **B** and there are version constraints, I cannot use **B** if **A** is installed in a venv.
Therefore it would be really nice to allow creating e.g. a venv and only install **B** in it. But keep everything in `pdm.lock`.

Maybe there is a workaround or a solution out there and I couldn't find it. 

Thank you all for your help

**Comment by pawamoy** [comment]
You can use `pdm install --no-default`.

**Reply by bitfoo1** [reply]
Thank you for your answer, but I do not quite get it. 
Would you please be so kind and give a little bit more information?

**Reply by pawamoy** [reply]
Sorry, I was answering to "Only install dev-dependencies group package (without prod) ": this is achieved with the `--no-default` flag, which prevents installing "production" dependencies. I'm not sure to understand the rest of your question.

> B has A as a dependency
> only install B

So, you want to install only **direct** dependencies and not **transitive** ones?

**Reply by bitfoo1** [reply]
Maybe I provide an excerpt from my pyproject.toml and the error which I get:
**pyproject.toml**:
```toml
[project]
name = "cdk-test"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Author", email = "mail"},
]
dependencies = [
    "cdk~=36.2.0",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]

pipeline = [
    "gcip~=12.5.2",
]
```

Error while trying to install **gcip~=12.5.2** which has a upper constraint on **cdk**:
```shell
> pdm add -dG pipeline "gcip~=12.5.2"
INFO: Adding group pipeline to lockfile
Adding packages to pipeline dev-dependencies: gcip~=12.5.2
🔒 Lock failed
WARNING: Unable to find a resolution for cdk
because of the following conflicts:
  cdk~=30.2 (from gcip@12.5.2)
  cdk~=30.2 (from gcip@12.5.3)
  cdk~=30.2 (from gcip@12.5.4)
  cdk~=30.2 (from gcip@12.5.5)
  cdk~=30.2 (from gcip@12.5.6)
  cdk~=36.2.0 (from project)
```

Removing the constraint is not possible, therefore I want to install gcip into an isolatet venv without installing cdk.
