### DISCUSSION TITLE
Make it really easy to add a dependency on a package in GitHub Enterprise (GHE)?

### DISCUSSION THREAD

**Discussion by msabramo** [pdm-project/pdm#2676] [Ideas]
I found that people in my workplace seemed to be largely unaware that they could make their projects depend on a git repo, either in public GitHub or in GitHub Enterprise (GHE). I also found that even if they did know this, they had to google the proper syntax of the URL to add every time they did this. Myself included. So I ended up writing a little utility command (with Typer; not a PDM plugin yet) that makes this easier. And then I wondered if perhaps I should convert this to a PDM plugin and possibly open-source it? But maybe there's already something out there that does this?

An example invocation and some code would probably help explain this better.

An example invocation of this command:

```shell
pdm ghe add some-cool-project our-org/some_cool_project
```

I do this by registering a PDM script in `pyproject.toml`:

```toml
[tool.pdm.scripts]
ghe.cmd = "python scripts/ghe.py"
```

And the code for `scripts/ghe.py` looks something like this:

```python
import os
import subprocess

import typer  # https://typer.tiangolo.com/
from typing_extensions import Annotated

app = typer.Typer()


@app.command(
def add(
    package_name: Annotated[
        str,
        typer.Argument(help="Python package name", show_default=False),
    ],
    repository_name: Annotated[
        str,
        typer.Argument(help="GHE repo in the form of <org>/<repo>", show_default=False),
    ],
    dev: Annotated[
        bool,
        typer.Option(help="Add packages into dev dependencies"),
    ] = False,
):
    cmd = ["pdm", "add"]
    if dev:
        cmd.append("--dev")
    cmd.append(
        f"{package_name} @ git+ssh://git@{os.getenv('GITHUB_ENTERPRISE_HOSTNAME')}/{repository_name}@main"
    )
    typer.echo(f"Running command: {cmd}\n")
    subprocess.run(cmd)


@app.callback()
def callback():
    """PDM utility commands for working with GitHub Enterprise (git.corp.adobe.com)."""


if __name__ == "__main__":
    app()

```

- Is there some PDM feature I'm unaware of that already does this?
- Any suggestions for improving the code I have?
- If not, could this possibly make a good PDM plugin?

**Comment by msabramo** [comment]
This almost seems like it could be a new type of package **source**, as described at https://pdm-project.org/latest/usage/config/#configure-the-package-indexes ?

Like what if one could do something like this:

```toml
[[tool.pdm.source]]
name = "github_public"
type = "github"
url = "git+ssh://git@github.com"

[[tool.pdm.source]]
name = "github_enterprise_private"
type = "github"
url = "git+ssh://git@githubenterprise.ourcompany.com"
```

?
