### DISCUSSION TITLE
Invalid use of `-p` parameter in pre-commit

### DISCUSSION THREAD

**Discussion by wu-clan** [pdm-project/pdm#2699] [Q&A]
```
project
   ├─ backend
   |     ├─ pdm.lock
   |     └─ pyproject.toml
   └─ .pre-commit-config.yaml
```
```yaml
repos:
  - repo: https://github.com/pdm-project/pdm
    rev: 2.12.4
    hooks:
      - id: pdm-export
        args:
          - '-p'
          - './backend'
          - '-o'
          - './backend/requirements.txt'
          - '--without-hashes'
        files: ^pdm.lock$
      - id: pdm-lock-check
        args:
          - '-p'
          - './backend'
```
Output when I execute the pre-commit command:
```
pdm-export-lock......................................(no files to check)Skipped
pdm-lock-check.......................................(no files to check)Skipped
```
The following commands can be executed and output normally.
```shell
pdm export -p ./backend -o ./backend/requirements.txt --without-hashes
```
