### DISCUSSION TITLE
Error when building site with pdm

### DISCUSSION THREAD

**Discussion by tvdboom** [pdm-project/pdm#2764] [Q&A] [answered]
Hi,

I am checking that building the documentation works within a Github Actions job that looks like this:

```
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up pdm
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.11"
          cache: true
      - name: Install dependencies
        run: pdm sync -G doc --no-default
      - name: Build documentation
        run: pdm run mkdocs build --strict
```

Within my `mkdocs.yml` file I use `pymdownx` to run a python script when building the docs.

```
markdown_extensions:
    - pymdownx.superfences:
        preserve_tabs: true
        custom_fences:
            - name: python
              class: python
              format: !!python/name:docs_sources.scripts.formatter
```

The directory `docs_sources` is at the top of [my repo](https://github.com/tvdboom/ATOM/tree/development). Unfortunately, running this yields the following error:

![image](https://github.com/pdm-project/pdm/assets/32366550/2412f52f-7a40-4d65-9b40-9ff5e2c02f08)

Before using `pdm`, I ran the command `mkdocs build` in the current `venv` and it worked correctly. Any ideas? Something related to the vitualenv?

Thanks
