### DISCUSSION TITLE
`no space left on device` error when using build with `pdm`

### DISCUSSION THREAD

**Discussion by tvdboom** [pdm-project/pdm#2773] [Q&A] [answered]
Hi,

I have been trying to get `pdm` to work with my CI on Github Actions but every time I get a `no space left on device` error. I do have many dependencies but not so many that I would expect it to take up all the available disk space.  Am I doing something wrong with my build? Any help is appreciated:)

The failing job looks like this:
```
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up pdm
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.11"
          cache: true
      - name: Install dependencies
        run: pdm sync -G full -G doc
      - name: Build documentation
        run: |
          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          pdm run mkdocs build --strict
```

Latest build with error: https://github.com/tvdboom/ATOM/actions/runs/8566270093/job/23475727347
yaml file: https://github.com/tvdboom/ATOM/blob/development/.github/workflows/config.yml
Dependencies: https://github.com/tvdboom/ATOM/blob/development/pyproject.toml#L22

P.S.: Before switching to `pdm`, I ran the build using `pip install -e .[full]` and that did work.

**Comment by pawamoy** [comment, marked as answer]
Looks like you're reaching the [~14GB of disk space](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). You can try this workaround: https://github.com/actions/runner-images/issues/2840#issuecomment-790492173.

Also, resolving your deps gave me 380 libraries, I'd say that's a lot indeed, especially when some of them are heavy ones (tensorflow, pandas, numpy, torch, etc.)

**Reply by tvdboom** [reply]
Thanks! That seemed to work. I have a follow up question. I'm running `pdm sync -G lint --no-default` to install the packages, which creates a new virtual env with python 3.10.

![image](https://github.com/pdm-project/pdm/assets/32366550/49c42009-2461-4aab-8f83-4f3880e50f5d)
![image](https://github.com/pdm-project/pdm/assets/32366550/f3972cfb-b975-4a1a-89cf-8d35476d5810)

How can I tell it to use Python 3.11? I am already using `setup-pdm` specifying the python version like this:

```
      - name: Set up pdm
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.11"
          cache: true
```

Or better yet. how can I tell it to use the current virtual env (which I assume is using the 3.11)?
