### DISCUSSION TITLE
Cache pdm environments in azure devops pipeline

### DISCUSSION THREAD

**Discussion by tvdboom** [pdm-project/pdm#2935] [Q&A] [answered]
Hi,

I have a devops pipeline that looks like this:

```
  - job: PreCommit
    pool:
      vmImage: ubuntu-latest
    variables:
      cache_dir: $(Pipeline.Workspace)/.cache
    steps:
      - task: UsePythonVersion@0
        displayName: "Use Python ${{ parameters.python_version }}"
        inputs:
          versionSpec: ${{ parameters.python_version }}

      - script: |
          echo "##vso[task.setvariable variable=PY]$(python -VV)"
        displayName: Set version variables

      - task: Cache@2
        displayName: Set caching
        inputs:
          key: pre-commit | .pre-commit-config.yaml | "$(PY)"
          path: $(cache_dir)

      - script: |
          python -m pip install -U pdm
          pdm sync -G lint --no-default
        displayName: Install dependencies
        env:
          PDM_CACHE_DIR: $(cache_dir)

      - script: |
          pdm run pre-commit run --all-files --show-diff-on-failure
        displayName: Run pre-commit
```

I want to cache two things here:

- The environment where `pdm` installs the libraries, to avoid reinstalling them next run of the pipeline.
- The cache of the pre-commit itself, to avoid reinstalling the pre-commit environment and running the same hooks every time.

I tried using the [Cache@2](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/cache-v2?view=azure-pipelines) task to cache directory `.cache`, but every run everything is reinstalled and reran again.

Within the pre-commit, I run mypy (among others) and in my `pyproject.toml` file I have 
![image](https://github.com/pdm-project/pdm/assets/32366550/62eba1c1-e583-4adc-88d9-caddeae2d07e)

Can anyone point what I am doing wrong? The [documentation](https://pdm-project.org/latest/usage/advanced/#use-pdm-in-continuous-integration) is not really helpful since it only talks about github actions.

Thanks
