### DISCUSSION TITLE
Flexibility for supporting package groups tied to specific sources (PyTorch issue)

### DISCUSSION THREAD

**Discussion by polarathene** [pdm-project/pdm#2968] [Q&A]
## Basic single source for specific packages

This will install `torch` and other deps by prioritizing the packages from the configured source in `pyproject.toml`. `include_packages` is required due to `respect-source-order = true` to avoid undesired behaviour.

```toml
[project]
name = "example"
requires-python = ">=3.10"
dependencies = [
    # Implicitly resolves `torch` to `2.3.1+cu121` via configured PyTorch source below (likewise for the other deps)
    "torch",
    "torchvision",
    "torchaudio",
]

# Packages defined in the `include_packages` of a source will prioritize resolution to that source, otherwise PyPi will be used first
# (avoids attempts to resolve packages to the PyTorch source, which logs many failures via `pdm outdated` or similar)
[tool.pdm.resolution]
respect-source-order = true

[[tool.pdm.source]]
name = "pytorch-cuda-12.1"
url = "https://download.pytorch.org/whl/cu121"
# Also ensure the transitive deps of `nvidia-*` packages are installed from this source, not PyPi (CUDA version mismatch)
include_packages = ["torch", "torchvision", "torchaudio", "nvidia-*"]
```

## Caveats when introducing multiple sources (_cannot restrict packages to sources via groups_)

Now you'd like the `pyproject.toml` for your app to support installing PyTorch with CUDA or CPU (_there's also ROCm for AMD, but let's keep it simple_):

```toml
[project]
name = "example"
requires-python = ">=3.10"
# Deps moved to optional groups
dependencies = []

# These will need to be explicitly requested via `-G` / `--group` during install:
[project.optional-dependencies]
torch_cpu = ["torch==2.3.1+cpu", "torchvision", "torchaudio"]
torch_cuda = ["torch==2.3.1+cu121", "torchvision", "torchaudio"]

[tool.pdm.resolution]
respect-source-order = true

# Now there are two PyTorch sources to consider:
[[tool.pdm.source]]
name = "pytorch-cuda-12.1"
url = "https://download.pytorch.org/whl/cu121"
include_packages = ["torch_cuda", "nvidia-*"]

[[tool.pdm.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
include_packages = ["torch_cpu"]
```

You'd then choose to install either via:

```bash
pdm install --group torch_cpu
pdm install --group torch_cuda
```

But unlike the prior example, the `torchvision` and `torchaudio` deps will install via PyPi.
- The `include_packages` for the referenced group is likely doing nothing and incorrect here.
- If you reverted `include_packages` to include the explicit `torch` / `torchvision` / `torchaudio` deps you'd find the CUDA source is resolved as it is defined first, thus `torch_cpu` is not able to use the correct source.

With the groups I was more explicit about the [_local identifier_](https://github.com/astral-sh/uv/blob/main/PIP_COMPATIBILITY.md#local-version-identifiers) being present (`+cpu` / `+cu121`), which only has support for `==` / `!=` with a version (_which is mandatory when paired with a local identifier unfortunately_).
- It would seem that you would need to do this for the `torchvision` and `torchaudio` packages too, keeping track of their explicit version to pin.
- That would be a bit more problematic however for the `nvidia-*` pattern, if you want to support the other _local identifiers_ for different versions of CUDA (additional sources).

There is one other caveat I've not mentioned thus far. PyTorch CPU source only has the `+cpu` _local identifier_ for the x86_64 package, the aarch64 / ARM64 package does not have that assigned, which complicates support there (_more details covered in a [related `uv` discussion](https://github.com/astral-sh/uv/issues/3437#issuecomment-2102125794)_). Meanwhile the CUDA group has no aarch64 packages (_despite nvidia having CUDA compatible products that run on aarch64, nvidia publishes it's own alternative to these PyTorch wheels sources for that_).

---

## Official advice for this scenario

Official advice appears to be to:
- Use groups like shown above, but with the _local identifiers_ and then producing separate lockfiles to install from: https://github.com/pdm-project/pdm/issues/2066#issuecomment-1612298770
- Use a single PyTorch source named `torch` and configure `pypi.torch.url` (_a bit vague, not enough context but presumably a CLI option?_): https://github.com/pdm-project/pdm/issues/2063#issuecomment-1611311613
- Only applicable for PyTorch specifically, use this plugin: https://github.com/EmbarkStudios/pdm-plugin-torch (_presently this plugin has been [broken for over 6 months](https://github.com/EmbarkStudios/pdm-plugin-torch/issues/24) despite a PR fix since March, it's also unclear if it really improves the DX due to how the plugin approaches solving the issue_)
