### DISCUSSION TITLE
ResolutionImpossible, duplicate requirement with contradicting Python version

### DISCUSSION THREAD

**Discussion by aeisenbarth** [pdm-project/pdm#3047] [Q&A]
For my project, PDM fails to resolve dependencies. I don't know whether I should do something differently, or something is wrong in the dependency, or in PDM (2.16.1):

**pyproject.toml**:
```toml
[project]
name = "pdm_resolve"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Person", email = "person@example.com"},
]
dependencies = [
    "prefect~=2.16",
]
requires-python = "<3.13,>=3.9"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
```
I did `pdm install` which takes very long and fails with the following log:
```
pdm.termui: Candidate rejected: prefect@2.16.0 because it introduces a new requirement pendulum<4,>=3.0.0; python_version >= "3.12" that conflicts with other requirements:
    pendulum<3.0; python_version < "3.12" (from prefect@2.16.0)
pdm.termui: Conflicts detected: 
  pendulum<3.0; python_version < "3.12" (from prefect@2.16.0)
  …
  pendulum<4,>=3.0.0; python_version >= "3.12" (from prefect@2.16.0)
  …
pdm.termui: Error occurs
resolvelib.resolvers.ResolutionImpossible: Unable to find a resolution
```
Looking at the dependency `prefect` shows that it lists a [duplicate requirement](https://github.com/PrefectHQ/prefect/blob/17f42e9d1d194a10010363c85ae28213f54aeaa3/requirements-client.txt#L19-L20):
```
pendulum < 3.0; python_version < '3.12'
pendulum >= 3.0.0, <4; python_version >= '3.12'
```
Apparently, this should mean, if Python < 3.12 select pendulum < 3.0, otherwise pendulum >= 3.0.0, <4. It seems PDM tries to find a way to fulfill both constraints at the same time.

- Is prefect's requirements specification correct? Does PDM support this type of constraints?
- Is there a way to avoid this with e.g. `[tool.pdm.resolution.overrides]`? Or do I have to constrain it to a single Python version?
