### DISCUSSION TITLE
How to properly switch from a released dependency to a pre-release

### DISCUSSION THREAD

**Discussion by b-morgenthaler** [pdm-project/pdm#3075] [Q&A] [answered]
Here's a work flow that did not work out quite well for me. Maybe anybody can help with it.

BTW: I am still using pdm in version 2.16.1 currently

At our company, we store the applications and libraries developed in two company internal pypi repositories: one for the released versions and for the pre-released (aka "dev") versions.

The additional, company internal pypi index are configured in pyproject.toml:

```toml
[tool.pdm.resolution]
respect-source-order = true
allow-prereleases = false  # set this to true if prereleases like development versions shall be resolved

[[tool.pdm.source]]
name = "company_pypi_default"  # this is just a proxy to official pypi.org/simple index
url = "https://company_server/repository/company_pypi_default/simple"
verify_ssl = false

[[tool.pdm.source]]
name = "company_pypi_internal"
url = "https://company_server/repository/company_pypi_internal/simple"
verify_ssl = false

[[tool.pdm.source]]
# only pre-releases/development versions are stored in the dev pypi repo
name = "company_pypi_internal_dev"
url = "https://company_server/repository/company_pypi_internal_dev/simple"
verify_ssl = false
```

Given I am developing on an app that depends on an internal library (no prerelease), the dependency is configured as follows:

```toml
dependencies = [
    "InternalLibrary>=1.1.0",
]
```

This works well, `InternalLibrary` is resolved from `company_pypi_internal` without any hustle.

But when I want to install the latest "dev" version for `InternalLibrary` in version 1.1.0, I switched this configuration in pyproject.toml:

```toml
[tool.pdm.resolution]
allow-prereleases = true
```

In the `company_pypi_internal_dev`, there are pre-releases published like `internallibrary==1.1.0.dev4455+g21c532cb`.

After changing this, I ran `pdm install` but the `InternalLibrary` always got resolved from `company_pypi_internal` with the released versions, I also tried `pdm sync -r` or deleting the lock file all together: the prereleases couldn't be resolved.

Am I thinking it wrong? Am I missing a configuration or command to make this scenario work?

Thanks in advance.

Appendix:

Here's the term output from running `pdm install` after the `allow-prereleases = true` change:

```ps
WARNING: Lockfile hash doesn't match pyproject.toml, packages may be outdated
Updating the lock file...
🔒 Lock failed
ERROR: Unable to find a resolution for internallibrary
Please make sure the package name is correct.
See C:\Users\[user]\AppData\Local\pdm\pdm\Logs\pdm-lock-j1g8h8zz.log for detailed debug log.
[ResolutionImpossible]: Unable to find a resolution
WARNING: Add '-v' to see the detailed traceback
```

And here's the debug log:

```text
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pytest>=8.2
pdm.termui:   pytest-cov
pdm.termui:   pytest-bdd
pdm.termui:   pytest-timeout
pdm.termui:   black
pdm.termui:   pylint
pdm.termui:   robotframework>=7.0
pdm.termui:   docutils
pdm.termui:   InternalLibrary>=1.1.0
pdm.termui:   python>=3.10.14
pdm.termui:   Adding requirement pytest>=8.2
pdm.termui:   Adding requirement pytest-cov
pdm.termui:   Adding requirement pytest-bdd
pdm.termui:   Adding requirement pytest-timeout
pdm.termui:   Adding requirement black
pdm.termui:   Adding requirement pylint
pdm.termui:   Adding requirement robotframework>=7.0
pdm.termui:   Adding requirement docutils
pdm.termui:   Adding requirement InternalLibrary>=1.1.0
unearth.collector: Collecting links from https://pypi.org/simple/internallibrary/
unearth.evaluator: Skipping link <Link https://pypi.org/simple/internallibrary/ (from None)>: Not a file: 
unearth.auth: Found index url https://pypi.org/simple/
unearth.collector: Failed to collect links from https://pypi.org/simple/internallibrary/: Client Error(404): Not Found
unearth.collector: Collecting links from https://company_server/repository/company_pypi_default/simple/internallibrary/
unearth.evaluator: Skipping link <Link https://company_server/repository/company_pypi_default/simple/internallibrary/ (from None)>: Not a file: 
unearth.auth: Found index url https://company_server/repository/company_pypi_default/simple/
unearth.collector: Failed to collect links from https://company_server/repository/company_pypi_default/simple/internallibrary/: Client Error(404): Not Found
unearth.collector: Collecting links from https://company_server/repository/company_pypi_internal/simple/internallibrary/
unearth.evaluator: Skipping link <Link https://company_server/repository/company_pypi_internal/simple/internallibrary/ (from None)>: Not a file: 
unearth.auth: Found index url https://company_server/repository/company_pypi_internal/simple/
unearth.collector: Fetching HTML page https://company_server/repository/company_pypi_internal/simple/internallibrary/
unearth.collector: Collecting links from https://company_server/repository/company_pypi_internal_dev/simple/internallibrary/
unearth.evaluator: Skipping link <Link https://company_server/repository/company_pypi_internal_dev/simple/internallibrary/ (from None)>: Not a file: 
unearth.auth: Found index url https://company_server/repository/company_pypi_internal_dev/simple/
unearth.collector: Fetching HTML page https://company_server/repository/company_pypi_internal_dev/simple/internallibrary/
pdm.termui: 	Could not find any matching candidates.
pdm.termui: Error occurs
Traceback (most recent call last):
  File "C:\Users\[user]\micromamba\envs\rf-internallibrary\Lib\site-packages\pdm\termui.py", line 257, in logging
    yield logger
  File "C:\Users\[user]\micromamba\envs\rf-internallibrary\Lib\site-packages\pdm\cli\actions.py", line 124, in do_lock
    raise ResolutionImpossible("Unable to find a resolution") from None
resolvelib.resolvers.ResolutionImpossible: Unable to find a resolution
```
