### DISCUSSION TITLE
Failure to install with Requested groups not in lockfile: dev

### DISCUSSION THREAD

**Discussion by cvgaviao** [pdm-project/pdm#3132] [Q&A]
After I have updated our Jenkins pipeline to use PDM 2.18.1 we started to get this error:

```
[Pipeline] sh
+ pdm install -G:all -v
[PdmUsageError]: Requested groups not in lockfile: dev
```
The pdm.lock was created with the same command on the laptop and pushed to git.

```
[metadata]
groups = ["default", "docs", "tests"]
strategy = ["inherit_metadata"]
lock_version = "4.5.0"
```

What am I missing here ?

**Comment by frostming** [comment]
I can't reproduce, can you provide an example repo?

Tested using this pyproject.toml:

```toml
[project]
name = "test_pdm"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "", email = "kukumav@example.com"},
]
dependencies = ["requests"]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
doc = ["mkdocs"]
test = ["pytest"]
```
