### DISCUSSION TITLE
Why does PDM behave extremely slow when I add a source (when trying to install CPU PyTorch) ?

### DISCUSSION THREAD

**Discussion by rishacha** [pdm-project/pdm#3316] [Q&A]
I'm using [this solution](https://github.com/pdm-project/pdm/issues/694#issuecomment-1488728288)

The config below works but causes pdm add/remove to work very slowly for some reason.
```toml
[[tool.pdm.source]]
type = "find_links"
url = "https://download.pytorch.org/whl/cpu/torch_stable.html"
name = "torch"
include_packages = ["torch*"]
```

How do I resolve this? Is this normal behaviour? Is there a better solution?
