### DISCUSSION TITLE
How to let pytest discovery in vscode to detect pytest in __pypackages__

### DISCUSSION THREAD

**Discussion by jamestansx** [pdm-project/pdm#595] [Q&A] [answered]
I have a pdm managed project with `pytest` installed. However, in vscode, it complains that pytest is not found despite the tests can still be running.  

![image](https://user-images.githubusercontent.com/45304579/128807498-c08e05f0-dff7-4c4a-8108-9b3fdfbd2ad5.png)
![image](https://user-images.githubusercontent.com/45304579/128807680-7d181ef3-1efd-4064-a4b3-0034d68ec104.png)

This is the error that it complains in the `pytest discovery` 
![image](https://user-images.githubusercontent.com/45304579/128807593-ef339ab6-4a46-46da-bc8c-498c37f26c46.png)

Is there any other settings that is needed to add? I have added the settings stated in the [docs](https://pdm.fming.dev/#vscode).

**Comment by frostming** [comment]
You'll need to set `python.testing.pytestPath` to `"__pypackages__/3.9/Scripts/pytest.exe"`, other standalone tools should be similar.

**Reply by c-warwick** [reply]
I don't have a `/Scripts`, but I have the below

![image](https://user-images.githubusercontent.com/84680804/158269444-5d29379d-3b01-41ea-9a79-49c7ea9228fe.png)

(M1 Mac) - not super sure where to point it at

`"python.testing.pytestPath": "${workspaceFolder}/__pypackages__/3.10/bin/pytest"` does not work.

**Reply by frostming** [reply]
`__pypackages__/3.10/bin/pytest`

**Reply by c-warwick** [reply]
Unfortunately this doesn't appear to be working - here are what I think the relevant files are, if you get a chance to look - very sorry to disturb, trying to understand how the pieces fit together so I can advocate more for PDM (and then, adopt/contribute to)

### .vscode/settings.json
```json
{
    "python.analysis.extraPaths": [
        "./__pypackages__/3.10/lib"
    ],
    "python.testing.pytestArgs": [
        "."
    ],
    "python.testing.unittestEnabled": false,
    "python.testing.pytestEnabled": true,
    "python.testing.pytestPath": "__pypackages__/3.10/bin/pytest"
}
```

### pyproject.toml
```toml
[project]
name = ""
version = ""
description = ""
authors = [
    ... ,
]
dependencies = [
    "boto3>=1.21.8",
]
requires-python = ">=3.10"
license = {text = "MIT"}
[project.optional-dependencies]

[tool.pdm.scripts]
start = "python example_athena_convert.py"
test = "pytest"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.0.1",
]
[project.urls]
Homepage = ""
[tool.pdm]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

```

### .pdm.toml
```toml
[python]
path = "/Users/<me>/.pyenv/versions/3.10.1/bin/python"
```

I will keep digging here as well, and I completely understand if you can't get to this. Thank you for all you do.
