### ISSUE TITLE
Configurable Lock File Location

### ISSUE THREAD

**Issue by Xdynix** [pdm-project/pdm#1038]
## Is your feature request related to a problem? Please describe.

I want to keep my project root as clean as possible. So I put all controllable configuration files like `pre-commit-config.yaml`, `.pylintrc`, `.coveragerc` etc into a separate folder. I want to do the same with `pdm.lock`.

## Describe the solution you'd like

The location of `pdm.lock` can be changed by setting in `pyproject.toml`, or by command line arguments. Something like:

```toml
# pyproject.toml
[tool.pdm]
# ...
lock_file = "config/pdm.lock"
```

or

```shell
pdm install --lock-file "config/pdm.lock"
```
