### ISSUE TITLE
Only `pdm-pep517` build system builds platform-specific wheels properly

### ISSUE THREAD

**Issue by adam-grant-hendry** [pdm-project/pdm#1132]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

1. Following same setup from [PDM Fails to Parse license-expression #1131 ](https://github.com/pdm-project/pdm/issues/1131)

2. Set `build-system` to different `PEP 517` backens:

```toml
[build-system]
requires = [
    "pdm-pep517>=0.12.0",
    "toml"
]
build-backend = "pdm.pep517.api"
```

```toml
[build-system]
requires = [
    "flit_core >=2,<4",
    "toml"
]
build-backend = "flit_core.buildapi"
```

```toml
[build-system]
requires = [
    "setuptools>=45",
    "wheel"
]
build-backend = "setuptools.build_meta"
```

## Actual behavior

Only `pdm-pep517` properly builds platform-specific wheel:

```powershell
PS> pdm build
Building sdist...
Built sdist at %USERPROFILE%/Code/myproj/dist\myroj-0.0.0.tar.gz
Building wheel...
Built wheel at %USERPROFILE%/Code/myproj/dist\myproj-0.0.0-cp38-cp38-win_amd64.whl
```

Others only build `-non-any` wheels:

```powershell
PS> pdm build
Building sdist...
Built sdist at %USERPROFILE%/Code/myproj/dist\emmy-0.0.0.tar.gz
Building wheel...
Built wheel at %USERPROFILE%/Code/myproj/dist\myproj-0.0.0-py3-none-any.whl
```

## Expected behavior

All `PEP 517`-compliant backends build platform-specific wheels.

## Environment Information

```bash
PDM version:        1.15.2
Python Interpreter: %USERPROFILE%\Code\myproj\.venv\Scripts\python.exe (3.8)
Project Root:       %USERPROFILE%/Code/myproj
Project Packages:   None
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.10",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19042",
  "python_full_version": "3.8.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "win32"
}
```
