### ISSUE TITLE
Long description

### ISSUE THREAD

**Issue by leandrodesouzadev** [pdm-project/pdm#1171]
Hey there!
I'm trying to put a long_description into the pypi.org website. I had used the description tag on the pyproject.toml, but the end result was not what i expected.  It populated the short-description that shows up on the packages list.
Is there anyway of using the readme.md as this long-description?
![](https://cdn.discordapp.com/attachments/824472777762275361/990934784572280832/unknown.png)

**Comment by ElijahSink** [comment]
How did you publish your package? With `twine`?

**Comment by leandrodesouzadev** [comment]
Yeah, i used twine.
By the way, my `pyproject.toml`looks like this:

```toml
[project]
name = "my-package"
version = "0.2.2"
description = """\
Long description here...
"""
requires-python = ">=3.9"
...
```
