### ISSUE TITLE
Can't resolve python interpreter 3.9

### ISSUE THREAD

**Issue by Whisht** [pdm-project/pdm#1303]
## Steps to reproduce
1. Install pdm on centos 7.6
2. run `pdm venv create 3.9`

## Actual behavior

 ` Can't resolve python interpreter 3.9` displayed .
![image](https://user-images.githubusercontent.com/16497652/182752990-7f737226-b20d-4c26-b575-4d7c621e990e.png)

Same problem happend with `pdm venv create 3.10`.

Does this means that I can only create venv with python version lower than pdm binded  version `3.8` ?
## Expected behavior
This command should create a virtual env with python interpreter 3.9.

## Environment Information

```bash
# pdm info
PDM version:
  2.1.0
Python Interpreter:
 ~/.local/share/pdm/venv/bin/python (3.8)
Project Root:
  ~
Project Packages:
  None
# psm info --env
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.13",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "3.10.0-1160.el7.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Mon Oct 19 16:18:59 UTC 2020",
  "python_full_version": "3.8.13",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
Check the `requires-python` in `pyproject.toml`

**Comment by Whisht** [comment]
It is just the default template created by `pdm init`.
```toml
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = [
    "virtualenv>=20.16.2",
]
requires-python = ">=3.8"
license = {text = "MIT"}

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
```
