### ISSUE TITLE
Support for PyPI core metadata `Home-page` similar to setuptools' `URL` or Poetry's `homepage`

### ISSUE THREAD

**Issue by rehanhaider** [pdm-project/pdm#1330]
## Is your feature request related to a problem? Please describe.
One of the core metadata supported is [home-page](https://packaging.python.org/en/latest/specifications/core-metadata/#home-page). This metadata (as far as I can tell, and I'm a noob) is `URL` in `setuptools` and `homepage` in `poetry`. 

The difference between this metadata and simply declaring the URL under `[project.urls]` in `pyproject.toml` is that the list under is sorted alphabetically, while `homepage` is always displated at top. 

### Declaring `homepage` under `[project.urls]` 

The following declaration in `pyproject.toml` results in the image below
```toml
[project.urls]
Homepage =  "https://github.com/rehanhaider/pyhtmlproofer"
Source = "https://github.com/rehanhaider/pyhtmlproofer"
Funding = "https://github.com/sponsors/rehanhaider"
```
![image](https://user-images.githubusercontent.com/4152163/185666121-aee17c29-ed89-4f4e-a3da-f6c7a4732fd8.png)

## Describe the solution you'd like

Ideally, I should be able to add `homepage` to `[tool.pdm.urls]` similar to `poetry` and this in turn would place `homepage` at top of the list instead of sorting it alphabetically. 

Considering `homepage` and `download-url` are two core metadata as per [PyPA guide](https://packaging.python.org/en/latest/specifications/core-metadata/#home-page) on package metadata this should be available.
