### ISSUE TITLE
Off-line installation with PDM

### ISSUE THREAD

**Issue by louis-xuy** [pdm-project/pdm#1372]

**Comment by frostming** [comment]
使用 `find_links`  作为唯一 source 参考[文档](https://pdm.fming.dev/latest/pyproject/tool-pdm/#find-links-source):

pyproject.toml:
```toml
[[tool.pdm.source]]
url = "file:///path/to/local/packages/folder"
name = "pypi"
type = "find_links"
```
