### ISSUE TITLE
`pdm install` without `-v` hangs when git prompts for credentials

### ISSUE THREAD

**Issue by 0xallie** [pdm-project/pdm#1455]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Create a pyproject.toml with the following contents:
```toml
[project]
name = "test"
dependencies = [
  "nonexistent @ git+https://github.com/nonexistent/nonexistent.git",
]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
```
2. Ensure you don't have any cached git credentials for GitHub.
3. Run `pdm install`.

## Actual behavior

PDM appears to hang at trying to install `nonexistent` as git is prompting for credentials. (Pressing Enter twice makes it error out.) I did not use `-v` as the issue doesn't happen when using `-v`.

## Expected behavior

It should either allow proper entry of the credentials (preferred, because I'd rather not have to see a bunch of verbose output just to be able to enter credentials) or at least error out with instructions to use `-v` instead of hanging forever.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
  2.1.5
Python Interpreter:
  /home/nyuszika7h/test/.venv/bin/python (3.10)
Project Root:
  /home/nyuszika7h/test
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.8",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.10.0-18-amd64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Debian 5.10.140-1 (2022-09-02)",
  "python_full_version": "3.10.8",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```
