### ISSUE TITLE
Run pre_install hook before checking if local path exists

### ISSUE THREAD

**Issue by nyuszika7h** [pdm-project/pdm#1458]
## Is your feature request related to a problem? Please describe.

I have the following in my pyproject.toml:
```toml
dependencies = [
  "bar @ file:///${PROJECT_ROOT}/bar",
]

[tool.pdm.scripts]
pre_install = "git submodule update --init"
```

However, this runs too late, so when the submodule is not initialized, it still results in this error:
```
[RequirementError]: The local path '/home/nyuszika7h/code/foo/bar' is not installable.
```

## Describe the solution you'd like

Run the `pre_install` hook before this check, or add another hook that runs before it.

**Comment by frostming** [comment]
It is not a good example, `git submodule update --init` is a prerequisite, and should not be run before *every* install.

**Comment by frostming** [comment]
Since `pre_install` would receive the *resolved* candidates at which point the requirements are already parsed, I would recommend using a custom script shortcut:

```toml
[tool.pdm.scripts]
pre_myinstall = "git submodule update --init"
myinstall = "pdm install"
```

Then `pdm myinstall` should work fine.
