### ISSUE TITLE
Install plugins from pyproject.toml (+config)

### ISSUE THREAD

**Issue by tgolsson** [pdm-project/pdm#1461]
## Is your feature request related to a problem? Please describe.

Hello!

To solve some workflow issues with torch I've developed a plugin that I'm storing in the same repository as the main project. I want all developers to have access to this tool for ease of use. However; there isn't any (documented?) way of putting a plugin into pyproject.toml, including configuration. I tried putting it in dev-dependencies, but since `pdm` runs in another environment it doesn't find the entrypoint.

## Describe the solution you'd like

I'd to be able to specify plugins and their configuration in the project.toml. The config part is roughly how I've done it today; but I'm just digging out the key from the `Project.pyproject` data. The first part I don't think exists at all.

```toml
[tool.pdm]
plugins = [
    "pdm_plugin_torch @ file:///${PROJECT_ROOT}/plugins/pdm-plugin-torch",
]

[tool.pdm.plugin.pdm_plugin_torch]
torch-version = "torch==1.10.2"
lockfile = "torch.lock"
enable-cpu = true

enable-rocm = true
rocm-versions = ["4.2"]

enable-cuda = true
cuda-versions = ["cu111", "cu113"]
```

A potential format version that's a bit more structured:

```toml
[[tool.pdm.plugins]]
dependency = "pdm_plugin_torch @ file:///${PROJECT_ROOT}/plugins/pdm-plugin-torch"

[tool.pdm.plugins.configuration]
torch-version = "torch==1.10.2"
lockfile = "torch.lock"
enable-cpu = true

enable-rocm = true
rocm-versions = ["4.2"]

enable-cuda = true
cuda-versions = ["cu111", "cu113"]
```

**Comment by tgolsson** [comment]
In case anyone finds this between now and a proper solution, this works quite well to solve half of it.
```toml
[tool.pdm.scripts]
post_install = "pdm plugin add plugins/pdm-plugin-torch"
```
