### ISSUE TITLE
Workspace support

### ISSUE THREAD

**Issue by frostming** [pdm-project/pdm#1505]

**Comment by noirbizarre** [comment]
That would be awesome.
Do you already have something in  mind ? Same approach as `Cargo` ?

**Comment by frostming** [comment]
Yes it would be similar to Cargo:

- `pdm init --workspace` to add a `tool.pdm.workspace` setting in `pyproject.toml`
- When the section is present, commands will turn into workspace mode -- will perform the same in subprojects
- `--include/--exclude` options to control the range of subprojects
- The lockfile will lock the dependencies in all subprojects.

**Comment by sanmai-NL** [comment]
What would be the best workaround for now to emulate this feature at the least cost, @frostming?

**Comment by frostming** [comment]
> What would be the best workaround for now to emulate this feature at the least cost, @frostming?

Using editable installs. Here is a simple example.

parent `pyproject.toml`:

```toml
[tool.pdm.dev-dependencies]
workspace = [
  "-e file:///${PROJECT_ROOT}/packages/foo#egg=foo",
  "-e file:///${PROJECT_ROOT}/packages/bar#egg=bar",
]
```
Metadata of `foo`: `packages/foo/pyproject.toml`:

```toml
[project]
name = "foo"
version = "0.1.0"

[build-system]
requires = ["pdm-pep517"]
build-backend = ["pdm.pep517.api"]
```
Metadata of `bar`: `packages/bar/pyproject.toml`:

```toml
[project]
name = "bar"
version = "0.1.0"
dependencies = ["foo"]  # specify dependency of other packages inside your workspace as named requirement

[build-system]
requires = ["pdm-pep517"]
build-backend = ["pdm.pep517.api"]
```

Then in the parent project, run: `pdm install`, will generate a `pdm.lock` and install `foo` and `bar` in editable mode into the environment. Since they are in editable mode, any modification to the `foo` or `bar` packages will take effect without reinstallation.

**Comment by lqhuang** [comment]
Background: major in Python, sometimes Scala (sbt) and Rust (cargo)

I also want to propose a file layout with my opinion. Here is an example of my
ideal PDM workspace:

```
.
├── docs
├── package-01
│   ├── docs
│   ├── pyproject.toml
│   ├── src
│   │   └── mynamespace
│   │       └── foo
│   └── tests
├── package-02
│   ├── docs
│   ├── pyproject.toml
│   ├── src
│   │   └── mynamespace
│   │       └── bar
│   └── tests
├── package-03
│   ├── docs
│   ├── mynamespace
│   │   └── baz
│   ├── pyproject.toml
│   └── tests
├── package-04
│   ├── docs
│   ├── pyproject.toml
│   ├── src
│   │   └── package_04
│   └── tests
├── package-05
│   ├── docs
│   ├── package_05
│   ├── pyproject.toml
│   └── tests
├── pyproject.toml
└── tests
```

And let me add some notes:

1. In my case, the reason I want to use mono-repo pattern for Python is I have
   several packages have the same top level namespace (or for enterprise
   internal tools, it could also be an org name) to maintain, but they are
   currently developed and released in different repos. So in my proposal
   `package-01`, `package-02` and `package-03` following
   [PEP420](https://peps.python.org/pep-0420/) have the same namespace, except
   `package-03` doesn't use `src` layout.
2. `package-04` and `package-05` stand for those standard way without own
   namespace and respectively layout with `src` or without `src`
3. All packages will have its own individual `tests` + `docs` directories and
   `pyproject.toml`

Other thoughts:

1. I place all packages in top level root for that I'm worried about overly nested
   directory level if `src` + `namespace` layout is applied. I think it's fine
   if this mono-repo is a pure Python project. But in some cases, those projects
   developed by multiple languages will have more complex structures. So it
   could be configurable like:

   ```toml
   [tool.pdm.workspace] # pyproject.toml in root dir
   packages = ["./*"]  # search by glob pattern
   packages = ["packages/*"]  # nodejs style
   packages = ["modules/*"]  # jvm style
   packages = ["src/*"]  # rust/c/c++ style

   packages = ["packages/foo", "packages/bar", "packages/baz"]  # manually specified
   ```

2. (Optional) Every sub-packages in mono-repo could be developed or run just
   like they are individual without top level tool. This would affect how to
   design the schema of sub-package's `pyproject.toml`. Of course, this probably
   is not necessary, unless somebody hopes he/she can do some simple develop
   routines to sub-package.

3. Sub-packages could share the same version defined in top level
   `pyproject.toml` and also use individual step-in version controlled by
   itself. For example, some packages will be released in the same time, then
   some auxiliary utils could be released in different schedules.

4. There are still `docs` and `tests` in top level root for a general entrypoint
   of docs' web and integrated tests for all sub-packages.

I create a [repo](https://github.com/lqhuang/pdm-workspace-examples) (which
could be transferred into PDM org) to illustrate current proposals of PDM
workspace. Maybe we could write some specifications there or use repo for
Unit tests and examples in the future.

Feedback is welcome and appreciated.

Finally, thanks for @frostming's efforts!

**Comment by carderne** [comment]
Just sharing my experience of trying to use pdm for a monorepo setup in case it's useful to anyone.
I used the [pdm-example-monorepo](https://github.com/pdm-project/pdm-example-monorepo) as a starting point

- You have to be careful running `pdm add ...` or anything in a sub-package, or it will try to create a brand new pdm project there for you (.venv, pdm.lock etc). This is annoying but I'm okay adding dependencies manually.
- `pdm run my_script` doesn't work from sub-packages, it just creates a fresh .venv etc and then fails. We could get around this by activating the venv and use Make but not great.
- Activating venvs from sub-packages doesn't really work...

Basically you can probably technically make it work, but you'll need to write a bunch of custom scripts to make the DX tolerable.

But it doesn't seem far to go, just some CLI sugar! I guess [monas](https://github.com/frostming/monas) is your (frontming) experiment to resolve this?

It seems like [rye](https://github.com/mitsuhiko/rye) is also quite close to supporting a sensible monorepo setup, but right now it doesn't properly handle relative directories for sub-packages which is a deal-breaker for a shared monorepo.

**Comment by jacksonwb** [comment]
How does building wheels work in this context?

**Comment by frostming** [comment]
> How does building wheels of packages with path dependencies work in this context?

I would prefer to specify dependency versions in sub packages, rather than specifying path dependencies, and those dependencies, if included by the workspace, will be installed with the local paths:

Something like:
```toml
[project]
dependencies = [
    "foo=={workspace_version}"
]
```

However, this is not valid PEP 621 metadata, which doesn't allow `${...}` in the version part.
