### ISSUE TITLE
Unable to include additional files inside of namespace package with subpackages when using pdm build

### ISSUE THREAD

**Issue by taranlu-houzz** [pdm-project/pdm#1574]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce
I have a project with this structure:

```
.
├── src
│   └── A
│       └── B
│           └── C
│               └── my_package
│                   ├── _private
│                   │   ├── data
│                   │   │   └── copyback_template.json
│                   │   ├── cli.py
│                   │   ├── constants.py
│                   │   ├── globals.py
│                   │   ├── lib.py
│                   │   └── logging.py
│                   └── __init__.py
├── pdm.lock
└── pyproject.toml
```

I am trying to include the `_private/data` dir when I build my package, but for some reason, it does not work, even when I add the path to the `includes` in my `pyproject.toml`:

```toml
####################################################################################################
# PDM
####################################################################################################


[tool.pdm]

[tool.pdm.build]
includes = ["src/A", "src/A/B/C/my_package/_private/data/"]

[tool.pdm.dev-dependencies]

[project]
name = "A.B.C.my_package"
version = "1.0.0a0"
description = "----"
authors = [{ name = "----", email = "----" }]
dependencies = [
    "boto3>=1.26.31",
    "httpx>=0.23.1",
    "rich>=12.6.0",
    "single-source>=0.3.0",
    "tenacity>=8.1.0",
    "typer[all]>=0.7.0",
]
requires-python = ">=3.11"

[project.optional-dependencies]

[project.scripts]
my_script = "A.B.C._private.cli:run_cli_app"


####################################################################################################
# Black
####################################################################################################


[tool.black]
line-length = 100

```

I've tried several different variations in the `include` section, including the full file path, but nothing seems to work...

## Actual behavior

The json in the `data` dir does not get included in the built package.

## Expected behavior

The json in the `data` dir should be included.

## Environment Information

```bash
❯ pdm info && pdm info --env
PDM version:
  2.3.3
Python Interpreter:
  ----/.venv/bin/python (3.11)
Project Root:
  ---
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.1",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "21.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64",
  "python_full_version": "3.11.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```
