### ISSUE TITLE
install development groups into separate environments

### ISSUE THREAD

**Issue by davidism** [pdm-project/pdm#1606]
Currently, all development groups get installed by default when calling `pdm install`/`sync`, and they're all installed in the same virtual environment. However, most development tools (tox, pre-commit, flake8, pdm, etc.) do not need to be installed in the same environment as the project code itself. And those tools can bring in their own dependencies and constraints on those dependencies. Some tools (pytest, sphinx, etc.) do need to be installed with the project.

An existing solution is to install those tools with pipx instead. However, I still want to have the versions of the tools pinned per-project. If I installed tox globally with pipx, I would have to ensure that every project works with that single version, which might be newer or older than what the project supports, depending on when a contributor last ran `pipx upgrade tox`.

I'm imagining an addition to the tool section in `pyproject.toml` to give an environment name to dev groups and scripts.

```toml
[tool.pdm.dev-dependencies]
tests = ["pytest", "blinker"]
tox = { env = "tox", deps = ["tox", "tox-pdm"] }
# or maybe same syntax as scripts section
tox.env = "tox"

[tool.pdm.scripts]
tox = "tox"
tox.env = "tox"
```

PDM would record that a given entry in the lock file is for a specific environment. It may need to multiple versions for different environments, for example pytest requires attrs>19.2.0, but another tool might depend on an older version. Currently that would result in a conflict, but now it could be resolved successfully in separate environments.

Now `pdm install` would install the project, its dependencies, and any dev groups that aren't associated with a separate environment. `pdm install -Dg tox` would set up the "tox" environment. `pdm run tox` would set up the environment and run the command against that environment.
