### ISSUE TITLE
.pdm.toml relative path

### ISSUE THREAD

**Issue by mgzenitech** [pdm-project/pdm#1620]
## Is your feature request related to a problem? Please describe.

Right now `.pdm.toml` stores absolute path to Python interpreter.

example:
```toml
[python]
path = "/home/marius/Documents/Projects/infra-terraform/.venv/bin/python"
```

## Describe the solution you'd like

I'd like it to store relative path to project:
```toml
[python]
path = ".venv/bin/python"
```

That way we could commit the `.pdm.toml` file and enforce everyone to use venv out of the box.

**Comment by pawamoy** [comment]
I don't think that's a good idea to enforce that. If only in-project virtualenvs are supported, I'd personally add a note in my CONTRIBUTING.md saying so.

I have no opinion about using a relative path though!

**Comment by mgzenitech** [comment]
In our company we have to preconfigure projects so that any user would just run `pdm install` and get everything configured/same environment.

We have managed to do it with pipenv and wanted to explore pdm as alternative as it is way faster when installing dependencies...

Main issues that are left:
1. Absolute paths in .pdm.toml
2. No plugin in pdm to automatically install Python version based on `requires-python = "==3.10.8"`

**Comment by frostming** [comment]
I don't think your prosed approach will help, because PDM will **ignore** the stored path if it doesn't exist.

As @pawamoy says, 

> If all PDM projects must always use an in-project venv, you could tell your devs to run this once:
> 
> ```
> pdm config python.use_venv true
> pdm config venv.in_project true
> ```

Also, make sure `__pypackages__` doesn't exist in your project, and this config will result in a consistent project structure.

**Comment by mgzenitech** [comment]
`.pdm.toml`in project's root would partially cover the problem, but doesn't pdm automatically add `path` to the file? In my tests pdm always added this:
```toml
[python]
path = "/home/marius/Documents/Projects/infra-terraform/.venv/bin/python"
```
thus rendering this file uncommitable and basically I've had to gitignore it...
