### ISSUE TITLE
`pdm install` prints errors for missing build dependencies in extra pypi indexes when using dynamic versioning

### ISSUE THREAD

**Issue by lukaszmoroz** [pdm-project/pdm#1635]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```toml
# pyproject.toml

[build-system]
requires = ["pdm-pep517", "setuptools"]
build-backend = "pdm.pep517.api"

[project]
name = "foo"
dynamic = ["version"]

[[tool.pdm.source]]
name = "example1"
url = "https://example.com/1/"

[[tool.pdm.source]]
name = "example2"
url = "https://example.com/2/"
```

or (2.4.0)

```toml
# ~/.config/pdm/config.toml

[pypi.example1]
url = "https://example.com/1/"

[pypi.example2]
url = "https://example.com/2/"
```

## Actual behavior

```console
$ pdm install
Failed to collect links from https://example.com/1/setuptools/: Client Error(404): Not Found
Failed to collect links from https://example.com/2/setuptools/: Client Error(404): Not Found
Failed to collect links from https://example.com/1/pdm-pep517/: Client Error(404): Not Found
Failed to collect links from https://example.com/2/pdm-pep517/: Client Error(404): Not Found
All packages are synced to date, nothing to do.
Installing the project as an editable package...
  ✔ Install foo 0.0.0 successful
```

Installing dependencies from `build-system.requires` with extra pypi indexes has a weird interaction with `dynamic = ["version"]`.

It prints `Failed to collect links` for every combination of a build dependency and an extra index where it's missing, despite being found in the default index and the installation completing normally.

This doesn't occur for install dependencies, nor when the project version is set statically. This is the minimal example I managed to pin the problem down to.

## Expected behavior

Those errors should not be logged in non-verbose mode.

## Environment Information

```
PDM version:
  2.4.0
Python Interpreter:
  <...>/foo/.venv/bin/python (3.10)
Project Root:
  <...>/foo
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.9",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.1.4-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Sat, 07 Jan 2023 15:10:07 +0000",
  "python_full_version": "3.10.9",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```
