### ISSUE TITLE
Listing optional dependencies inside `[project.optional-dependencies]`?

### ISSUE THREAD

**Issue by baggiponte** [pdm-project/pdm#1694]
I noticed there is a field in the pyproject.toml specification that allows listing optional dependencies ([here](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#dependencies-optional-dependencies)):

```toml
[project.optional-dependencies]
gui = ["PyQt5"]
cli = [
  "rich",
  "click",
]
```

To be fair, I feel this was "fairly" recent (did not notice the first time I read the pypa specification).

Is there a blocking reason for which `pdm` lists dev dependencies inside `[tool.pdm.dev-dependencies]`? Glad to help if anyone believes `pdm` should be compatible with this logic.
