### ISSUE TITLE
Cannot import "apt" as a site package

### ISSUE THREAD

**Issue by lofidevops** [pdm-project/pdm#1787]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

Related issues? https://github.com/pdm-project/pdm/issues/985 https://github.com/pdm-project/pdm/issues/634

## Background

For various reasons, installing `apt` into a virtualenv is tricky. With other package managers I've found it easier to just use `site-packages` (sometimes called "system packages"). But I'm struggling to achieve the same result with pdm.

A simple test is that a script with "import apt" should run without error.

## Steps to reproduce

Create a pdm project with the following files. Then try `pdm install --dev --no-isolation` and `pdm run -v --site-packages spsample`

**pyproject.toml**

```toml
[project]
name = "spsample"
version = "0.0.1"
description = "Example using site packages."
requires-python = ">=3.10"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project.scripts]
spsample = "spsample.cli:invoke"
```
**src/spsample/cli.py**

```python
import apt


def invoke():
    print("Hello world!")


if __name__ == "__main__":
    invoke()
```

## Actual behavior

```
Traceback (most recent call last):
  File "/home/user/spsample/.venv/bin/spsample", line 5, in <module>
    from spsample.cli import invoke
  File "/home/user/spsample/src/spsample/cli.py", line 1, in <module>
    import apt
ModuleNotFoundError: No module named 'apt'
```

## Expected behavior

Should print "Hello world!" after importing the system package called apt.

## Environment Information

```bash
PDM version:
  2.4.9
Python Interpreter:
  /home/user/spsample/.venv/bin/python (3.10)
Project Root:
  /home/user/spsample
Project Packages:
  None
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.19.0-35-generic",
  "platform_system": "Linux",
  "platform_version": "#36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2",
  "python_full_version": "3.10.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```

**pdm list -v --graph**

```
spsample 0.0.1+editable [ Not required ]
```
