### ISSUE TITLE
``pdm show --version`` doesn't output the version anymore

### ISSUE THREAD

**Issue by mikedingjan** [pdm-project/pdm#1788]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

```bash
pdm show --version
```

## Actual behavior

output: DYNAMIC

## Expected behavior

output: version number from SCM

## Environment Information

Config:

```toml
[tool.pdm.version]
source = "scm"

[project]
...
dynamic = ["version"]
...
```

```bash
PDM version:
  2.4.9
Python Interpreter:
  /opt/homebrew/opt/python@3.11/bin/python3.11 (3.11)
Project Root:
  /Users/..../Projects/.../terraform-django
Project Packages:
  /Users/..../Projects/.../terraform-django/__pypackages__/3.11
```
