### ISSUE TITLE
is it possible to specify different requires-python range per optional dep group?

### ISSUE THREAD

**Issue by wey-gu** [pdm-project/pdm#1794]
## Is your feature request related to a problem? Please describe.

I am not sure if this reason conflicts with existing assumptions, but I really hit a scenario that my different two optional dep groups are mutually exclusive, and they are so different that each required a different range of python.

Is this even possible from the PDM scope? Or it had to be at the PEP level?

## Describe the solution you'd like

The `requires-python` under `project.optional-dependencies.xxx` will be a subset of the project scope one:

It could be something like this:

```toml
[project]
requires-python = ">=3.7.1,<3.10"
[project.optional-dependencies.extra_foo]
requires-python = ">=3.9,<3.10"
[project.optional-dependencies.extra_far]
requires-python = ">=3.7.1,<3.9"
```

Do you think this makes sense?

Thanks!
