### ISSUE TITLE
Support pdm.toml configuration in pyproject.toml

### ISSUE THREAD

**Issue by wgordon17** [pdm-project/pdm#1828]
With the change from a hidden `.pdm.toml` configuration to a `pdm.toml` file, I'm requesting the ability to migrate this configuration into the `[tool.pdm]` configuration section of `pyproject.toml`.

The goal (or at least _my_ goal) with `pyproject.toml` is to unify configuration of the myriad of tooling into a single file. Many tools have come a long way to making this a reality, greatly reducing my configuration file sprawl.

When `.pdm.toml` was just a hidden file, it was easier to ignore/justify, but now that's _in your face_, I would like to get rid of this file and migrate it's configuration into `pyproject.toml`.

So `pdm.toml` configuration would move from

```toml
[python]
use_venv = true

[strategy]
save = "compatibility"

[venv]
in_project = false
```

To `pyproject.toml`

```toml
[tool.pdm.python]
use_venv = true

[tool.pdm.strategy]
save = "compatibility"

[tool.pdm.venv]
in_project = false
```
