### ISSUE TITLE
pdm install --plugins error

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#1987]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

The docs recommend to add this:

```toml
[tool.pdm]
plugins = [
    "-e file:///{PROJECT_ROOT}"
]
```

...and run this:

```
pdm install --plugins
```

...when developing a PDM plugin to install it in editable mode.

However I'm getting this error:

> [RequirementError]: Editable requirement is only supported for VCS link or local directory.

## Steps to reproduce

Work in a plugin project, set PDM plugins in pyproject.toml as described above, run `pdm install --plugins`.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.7.0
Python Interpreter:
  /home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.11.0/bin/python3 (3.11)
Project Root:
  /media/data/dev/pdm-multirun
Local Packages:
  /media/data/dev/pdm-multirun/__pypackages__/3.11
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.0",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.3.6-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Mon, 05 Jun 2023 15:12:57 +0000",
  "python_full_version": "3.11.0",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

**Comment by frostming** [comment]
Can't reproduce, here is the pyproject.toml:

```toml

[project]
name = "test-pdm"
version = "0.1.0"
description = ""
authors = [
    {name = "Frost Ming", email = "me@frostming.com"},
]
dependencies = [
    "anyio>=3.7.0",
]
requires-python = ">=3.10,<3.12"
readme = "README.md"
license = { text = "MIT" }


[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
plugins = [
    "-e file:///${PROJECT_ROOT}",
]
```
