### ISSUE TITLE
ExtrasWarning: Extras not found for jax: [cuda12_pip]

### ISSUE THREAD

**Issue by lc6chang** [pdm-project/pdm#2006]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Prepare a pdmworkspace
   ```bash
   mkdir pdmworkspace
   cd pdmworkspace
   ```
2. Create `pyproject.toml`:
    ```toml
    [project]
    dependencies = [
        "jaxlib@https://storage.googleapis.com/jax-releases/cuda12/jaxlib-0.4.10%2Bcuda12.cudnn88-cp310-cp310-manylinux2014_x86_64.whl",
        "jax[cuda12_pip]==0.4.11",
    ]
    requires-python = ">=3.10"
    ```
3. Install
    ```bash
    pdm install
    ```
## Actual behavior

Successfully installed with:
```
Lock file does not exist
Updating the lock file...
python.use_venv is on, creating a virtualenv for this project...
Virtualenv is created successfully at /home/.../pdmworkspace/.venv
/home/.../.local/lib/python3.10/site-packages/pdm/models/candidates.py:573: ExtrasWarning: Extras not found for jax: [cuda12_pip]
  return filter_requirements_with_extras(
🔒 Lock successful
Changes are written to pdm.lock.
Synchronizing working set with lock file: 6 to add, 0 to update, 0 to remove

  ✔ Install opt-einsum 3.3.0 successful
  ✔ Install jax 0.4.11 successful
  ✔ Install ml-dtypes 0.2.0 successful
  ✔ Install numpy 1.24.3 successful
  ✔ Install scipy 1.9.3 successful
  ✔ Install jaxlib 0.4.10+cuda12.cudnn88 successful

🎉 All complete!
```
## Expected behavior
No `ExtrasWarning: Extras not found for jax: [cuda12_pip]`, but installed the extra deps like these:
https://github.com/google/jax/blob/9b10384b430231d42b215a14aa09c127e52ec586/setup.py#L111-L121

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.7.2
Python Interpreter:
  /home/.../pdmworkspace/.venv/bin/python (3.10)
Project Root:
  /home/.../pdmworkspace
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.19.0-41-generic",
  "platform_system": "Linux",
  "platform_version": "#42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2",
  "python_full_version": "3.10.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```
