### ISSUE TITLE
Variable expansion at lock time for package indexes

### ISSUE THREAD

**Issue by bilelomrani1** [pdm-project/pdm#2063]
## Is your feature request related to a problem? Please describe.

In my project I need to generate two distinct lockfiles, one for a CPU Docker image and another one for a GPU Docker image containing all the necessary CUDA runtime. Pytorch distributes several versions of `torch` located at different package indexes depending on the targeted accelerator, for instance https://download.pytorch.org/whl/cpu for a CPU-only wheel.

I would like to easily pin two lockfiles, one in which `torch` is installed from https://download.pytorch.org/whl/cpu and another one where `torch` is installed from https://download.pytorch.org/whl/cu118, using the same pyproject.toml.

## Describe the solution you'd like

Using an environment variable $TORCH_INDEX_SLUG extrapolated at locking time, something like this

```toml
[project.optional-dependencies]
cpu = ["torch==2.0.1+cpu"]
gpu = ["torch==2.0.1+cu118"]

[[tool.pdm.source]]
name = 'torch'
url = 'https://download.pytorch.org/whl/$TORCH_INDEX_SLUG'
type = 'index'
```

```bash
TORCH_INDEX_SLUG=cpu pdm lock --dev -G cpu -L lockfiles/pdm-cpu.lock
TORCH_INDEX_SLUG=cu118 pdm lock --dev -G gpu -L lockfiles/pdm-gpu.lock
```
