### ISSUE TITLE
Documentation: Describe how to configure dynamic package versioning using scm/git

### ISSUE THREAD

**Issue by vlcinsky** [pdm-project/pdm#2089]
This issue is proposing an update of pdm documentation with regards to declaring package version.

# Current status (as of pdm version 2.7):
pdm allows to specify in `pyproject.toml` a package version in multiple ways.

## Static
```toml
[project]
version = "1.0.0"
```
The version is explicitly stated in the `pyproject.toml`.

## Dynamic (from a file): 
```toml
[project]
...
dynamic = ["version"]

[tool.pdm]
version = { source = "file", path = "mypackage/__version__.py" }
```
The version is read from a file (here `mypackage/__version__.py`) which is typically managed by some external tool such as bumpversion.
## Dynamic (from scm/git)
```toml
[project]
...
dynamic = ["version",]
...
[tool.pdm.version]
source = "scm"
```
The version is derived from the latest tag in (git) source control. If current commit is tagged, the version is read from the tag as is, if the tag is present is some commit behind, version string is derived from given tag and current commit hash.

## Documentation describes only the first two options
The problem is, that the "Dynamic (from scm/git)" option is not described in the documentation and it is not easy to find it.

# Proposed solution

Update the [PEP 621 Metadata/Package version](https://pdm.fming.dev/2.8/reference/pep621/#package-version) as follows:
- Keep the "Static" tab
- Rename the "Dynamic" tab to "Dynamic (from a file)", remove the link "dynamic versioning" as it does not lead to useful instructions.
- Add new tab named "Dynamic (from scm/git)" and add very short description as shown above.

# Alternative solution
Alternatively we may update "Build configuration/dynamic versioning" section which seems to be currently intended but is actually missing.

# Points to review
I have tested the dynamic versioning with scm/git for `pdm.backend`

```toml
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
```
It is very likely, that each backend may offer a bit different options for assigning version. In such a case, it would be better to use dedicated section for each backend and in that place describe (for pdm-backend) or refer to (for other backends) how is versioning and possibly other aspects of package build configured and managed.
