### ISSUE TITLE
feat: provisional lifecycle hooks

### ISSUE THREAD

**Issue by aarnphm** [pdm-project/pdm#2110]
Currently, the `pre_*` and `post_*` hooks are run before and after, correspondingly for any user's script.

However, in some cases, we only want to run these scripts on different environments depending on envvar. One example usage maybe whether my tests are independent of which torch installation I'm using, so I only want to install CPU variant of Torch on GITHUB_ACTIONS.

It would be nice if we can support the following:

```toml
[tool.pdm.scripts]
pre_test  = {cmd = "pip install torch torchaudio torchvision --index-url https://download.pytorch.org/whl/cpu", env = "GITHUB_ACTIONS"}
test = ...
post_test = { ... }
```

cc @frostming
