### ISSUE TITLE
Lock expands linked filepaths, making pdm.lock not portable at all, not just platform specific.

### ISSUE THREAD

**Issue by Jackbennett** [pdm-project/pdm#2240]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

That said, I suspect the answer involves the workspaces issue.

## Steps to reproduce

Building the parent monorepo project and dependencies expands filepaths in the lockfile.

for example;

parent `pyproject`: 
```toml
[tool.pdm.dev-dependencies]
dev = [
  "-e foo @ file:///${PROJECT_ROOT}/packages/foo#egg=foo",
  "-e bar @ file:///${PROJECT_ROOT}/packages/bar#egg=bar",
]
```

foo `pyproject` depends on bar:

```toml
[tool.pdm.dev-dependencies]
dev = [
  "-e file:///${PROJECT_ROOT}/packages/../bar#egg=bar",
]
[project]
dependencies = [
  "bar @ file:///${PROJECT_ROOT}/packages/../bar#egg=bar"
]
```

The `pdm.lock` contains an expanded path;
```
dependencies = [
    "bar @ file:///workspace/persist/monorepo/packages/foo/../bar",
]
```
and when `pdm export` runs the filepath is also expanded in the requirements.txt. So if I run `pdm sync` in CI, this doesn't resolve bar.

Now, hopefully I've made a error in the structure as it was hard to find references. But if I'm supposed to build the file dependency package first I did not find how.
