### ISSUE TITLE
In dockerfile use pdm

### ISSUE THREAD

**Issue by vvanglro** [pdm-project/pdm#2244]
This dockerfile:

```dockerfile
FROM python:3.8-slim

RUN mkdir /workspace/
WORKDIR /workspace/
ADD . /workspace/
ENV TZ=Asia/Shanghai
ENV EXTERNAL_PYPI_SERVER=https://pypi.tuna.tsinghua.edu.cn/simple
RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list.d/debian.sources && \
    sed -i 's/security.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list.d/debian.sources && \
    apt update && \
    ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    python -m venv /opt/venv && \
    pip install --no-cache-dir -i $EXTERNAL_PYPI_SERVER --upgrade pip && \
    pip install --no-cache-dir -i $EXTERNAL_PYPI_SERVER --upgrade pip pdm && \
    pdm sync --prod && \
    pdm cache clear
ENTRYPOINT ["pdm", "run"]
```

docker-compose:
```yml
version: "3.8"

services:
  web:
    build: .
    volumes:
      - $PWD/:/workspace
    command:
      - /bin/bash
      - -c
      - |
        alembic upgrade head
        yacron -c cron/crontab.yaml -l DEBUG &
        gunicorn asgi:app -b 0.0.0.0:8000 -w 4 -k uvicorn.workers.UvicornWorker --access-logfile -
    ports:
      - "8081:8000"
    restart: always
    tty: true
    stdin_open: true
    logging:
      options:
        max-size: "50m"
```

![image](https://github.com/pdm-project/pdm/assets/43594924/66d4ebcc-19e7-4fbb-9c7d-5c8f907b5b81)

When I use docker-compose to start, the command cannot be found, and the command is normal after I run a one-time container.

The .pdm-python file is not versioned, so it should not be a problem with this file.

I don't know where is the problem.
