### ISSUE TITLE
have a pdm shell command

### ISSUE THREAD

**Issue by deronnax** [pdm-project/pdm#2249]
## Is your feature request related to a problem? Please describe.

No

## Describe the solution you'd like

A `pdm shell` command, like Pipenv, Poetry and Hatch have. I have seen `pdm venv activate` but it isn't really the same (plus it does not seem to work).

**Comment by pawamoy** [comment]
Workaround in the meantime, if you install dependencies in `__pypackages__`:

```toml
# pyproject.toml
[tool.pdm.scripts]
shell = {shell = "PATH=$(echo $(pdm info | grep __pypackages__)/bin):$PATH zsh"}
```

```console
% type ruff
ruff not found
% pdm run shell
% type ruff
ruff is /media/data/dev/griffe/__pypackages__/3.11/bin/ruff
```

**Comment by deronnax** [comment]
Wow, hat's a good workaround, thank you.

**Comment by pawamoy** [comment]
You're welcome! The following seems to work for venvs:

```toml
# pyproject.toml
[tool.pdm.scripts]
shell = {shell = "zsh -c \"eval $(pdm venv activate 3.11); export PATH; export VIRTUAL_ENV; exec zsh\""}
```
