### ISSUE TITLE
`pdm update -u` moves `[tool.pdm]` section to the bottom of `pyproject.toml`

### ISSUE THREAD

**Issue by killjoy1221** [pdm-project/pdm#2251]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Given a pyproject.toml like this.
```toml
[project]
name = "foobar"
version = "0.0.0"
requires-python = ">=3.7,<4.0"

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
  "pytest>=6.0.0"
]

[build-system]
requires= ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pytest.ini_options]
addopts = "--someoptions"
```

## Actual behavior

Running `pdm update -u` will create a `pyproject.toml` that looks like this.
```toml
[project]
name = "foobar"
version = "0.0.0"
requires-python = ">=3.7,<4.0"

[build-system]
requires= ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pytest.ini_options]
addopts = "--someoptions"

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
  "pytest>=7.4.2"
]

```

## Expected behavior
I expect it to keep the same order of keys when writing back to the file system.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
❯ pdm info && pdm info --env
PDM version:
  2.9.1
Python Interpreter:
  .../project/.venv/bin/python (3.10)
Project Root:
  .../project
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.12",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.90.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Fri Jan 27 02:56:13 UTC 2023",
  "python_full_version": "3.10.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
     
```
