### ISSUE TITLE
How to "temporarily install packages for a one-time script"?

### ISSUE THREAD

**Issue by UnoYakshi** [pdm-project/pdm#2298]
# Context
For downloading a couple of files from MLFlow server in my Docker image, I need to temporarily add `mlflow` and `boto3` packages to the project (to call a Python script). For now, I use `pre_download_script`, `download_script`, and `post_download_script` in `pyproject.toml`.
However, I definitely don't need those dependencies in production (like any other dev-dependencies).

```toml
pre_download_script = "pdm add --no-editable mlflow boto3"
# Or...
pre_download_script = "pdm sync --no-editable -dG download_models"

download_script = "pdm run download.py"

post_download_script = "pdm remove mlflow boto3"
# Or...
post_download_script = "pdm remove -dG download_modes mlflow boto3"
```

The problem with the first option (w/o the dev group) is that it installs dev-dependencies, too. What am I doing wrong?
The second option throws `ModuleNotFoundError: No module named 'pkg_resources'` at me; however, I thought I configured `pdm.lock` correctly.

# Best Practice?
Is there a better practice to achieve similar effect? What's the canonical way to wrap a PDM script with packages? Perhaps, should I create a separate virtual environment for that instead?
