### ISSUE TITLE
Feature Request: Specify Index for Individual Dependencies

### ISSUE THREAD

**Issue by gbottari** [pdm-project/pdm#2307]
I am managing a project with dependencies that must be fetched from multiple sources, including PyPI and a private registry hosted on Azure. Currently, it seems there isn't a straightforward way to specify the index for individual dependencies directly in `pyproject.toml`.

## Proposal

I propose a feature similar to how Pipenv and Poetry handle index specifications for individual dependencies. This will allow for specifying the index/source of each dependency within `pyproject.toml`. Below are examples from Pipenv and Poetry for reference:

In Pipenv ([docs](https://pipenv.pypa.io/en/latest/indexes/#index-restricted-packages)):
```toml
[[source]]
url = "https://pypi.org/simple"
name = "pypi"

[[source]]
url = "https://private-registry.example.com/simple"
name = "private"

[packages]
requests = {version="*", index="pypi"}
private-package = {version="*", index="private"}
```

In Poetry ([docs](https://python-poetry.org/docs/pyproject/#dependencies-and-dependency-groups)):
```toml
[[tool.poetry.source]]
name = "private"
url = "https://private-registry.example.com/simple"

[tool.poetry.dependencies]
requests = "*"
private-package = { version = "*", source = "private" }
```

Given that PDM uses the `[project]` and `[tool.pdm.dev-dependencies]` sections to list dependencies, I would just add a mapping on the `tool.pdm.resolution` section for each dependency that comes from the secondary source.

In PDM:
```toml
[project]
dependencies = [
    "requests",
    "private-package",
]

[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"

[[tool.pdm.source]]
name = "private"
url = "https://private-registry.example.com/simple"

[tool.pdm.resolution]
private = [
   "private-package",
]
```

This feature would be handy in scenarios where specific dependencies are only available in a private registry, or when there's a need to fetch specific versions of dependencies from particular sources.
