### ISSUE TITLE
pdm-export-lock: "PDM 0.1.dev1+g5861d12 is installed, while 2.9.3 is available."

### ISSUE THREAD

**Issue by anentropic** [pdm-project/pdm#2312]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

I have a `.pre-commit-config.yaml` with the following:

```yaml
  - repo: https://github.com/pdm-project/pdm
    rev: 2.9.3
    hooks:
      - id: pdm-lock-check
      - id: pdm-export
        args: ['-o', 'requirements-ci.txt', '-G', 'default,ci', '--without-hashes']
        files: ^pdm.lock$
```

## Actual behavior

When the pre-commit hooks run I see output like this:

```
pdm-lock-check...........................................................Passed
pdm-export-lock..........................................................Failed
- hook id: pdm-export
- files were modified by this hook

The exported requirements file is no longer cross-platform. Using it on other
platforms may cause unexpected result.

PDM 0.1.dev1+g5861d12 is installed, while 2.9.3 is available.
Please run `pdm self update` to upgrade.
Run `pdm config check_update false` to disable the check.
```

Specifically this part `PDM 0.1.dev1+g5861d12 is installed, while 2.9.3 is available.` seems odd.

## Expected behavior

I thought that:

```yaml
  - repo: https://github.com/pdm-project/pdm
    rev: 2.9.3
```

...should ensure the pre-commit hook is running pdm version 2.9.3

but the `pdm-export-lock` hook seems to think it's running a weird random old version for some reason.

## Environment Information

```bash
PDM version:
  2.9.3
Python Interpreter:
  /Users/anentropic/myproject/.venv/bin/python (3.11)
Project Root:
  /Users/anentropic/myproject
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.5",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "22.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112",
  "python_full_version": "3.11.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
The PDM version is determined using SCM instead of encoded statically in a file. While pre-commit hook does not clone the full history of the git repo, so you see the version is 0.1x.

Nothing we can improve here. You should consider disabling the warning as it says.

**Comment by toppk** [comment]
if I disable this wouldn't it disable it across the board?  Somehow I should want to disable it only for pre-commit pdm launches where the version information is invalid.

**Comment by JacobHayes** [comment]
Looks like there's [a `PDM_CHECK_UPDATE` env var](https://pdm-project.org/latest/reference/configuration/#available-configurations) that can be set. "Unfortunately", `pre-commit` [doesn't seem to support](https://github.com/pre-commit/pre-commit/issues/1157) setting env vars without just overriding the whole entry, so I'm using:
```yaml
  - repo: https://github.com/pdm-project/pdm
    rev: 2.12.3
    hooks:
      - id: pdm-lock-check
        entry: env PDM_CHECK_UPDATE=false pdm lock --check
      - id: pdm-export
        entry: env PDM_CHECK_UPDATE=false pdm export
        args: ["-o", "requirements.release.lock.txt"]
        files: ^(pdm.lock|requirements.release.lock.txt)$
      - id: pdm-sync
        entry: env PDM_CHECK_UPDATE=false pdm sync
```
---
@frostming would you accept a PR adding those `env`s to the [`.pre-commit-hooks.yaml`](https://github.com/pdm-project/pdm/blob/main/.pre-commit-hooks.yaml) so users don't need to override?

I'm not certain how / if that'd work on (non-WSL) Windows.
