### ISSUE TITLE
pdm export requirements does not use --find-links

### ISSUE THREAD

**Issue by ethanluoyc** [pdm-project/pdm#2342]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

I would like to export a requirements.txt file for installation. In my pyproject.toml I have 

```toml
[project]
dependencies = ['jax[cuda12_pip']
[[tool.pdm.source]]
name = "jax_cuda"
url = "https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"
verify_ssl = true
type = "find_links"
```
However when I export requirements file, these are exposed as `--extra-index-url` as opposed to --find-links.

## Actual behavior

At the end of my exported requirements I get
```
--extra-index-url https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```

## Expected behavior

I expect the find links in sources to be preserved during export. The above should be 

```
--find-links https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.10.0
Python Interpreter:
  /home/yicheng/project/.venv/bin/python (3.10)
Project Root:
  /home/yicheng/project/
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.10.5",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.0-87-generic",
  "platform_system": "Linux",
  "platform_version": "#97~20.04.1-Ubuntu SMP Thu Oct 5 08:25:28 UTC 2023",
  "python_full_version": "3.10.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```
