### ISSUE TITLE
Installation failed when install.cache = true

### ISSUE THREAD

**Issue by ethanluoyc** [pdm-project/pdm#2355]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

The output is very lengthy, but the interesting bit is 

```
IsADirectoryError: [Errno 21] Is a directory: '/home/name/projects/pdm-example/.venv/lib/python3.10/site-packages/examples'
```

## Steps to reproduce

Here is my pyproject.toml.
```toml

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "pdm-example"
version = "0.1.0"
description = ""
authors = [{ name = "Yicheng Luo", email = "ethanluoyc@gmail.com" }]
dependencies = [
    "rlax>=0.1.6",
]
requires-python = ">=3.10,<3.11"
readme = "README.md"
license = { text = "MIT" }

[[tool.pdm.source]]
name = "jax_cuda"
url = "https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"
verify_ssl = true
type = "find_links"

[tool.pdm.dev-dependencies]
dev = ["pytest>=7.4.3", "pytest-xdist>=3.3.1"]

```
You can use a Dockerfile to reproduce this.

```
# build stage
FROM python:3.10-slim

# install PDM
RUN pip install -U pip setuptools wheel
RUN pip install pdm

# copy files
COPY pyproject.toml README.md /project/

# install dependencies and project into the local packages directory
WORKDIR /project
RUN pdm config install.cache true && pdm install

```

## Actual behavior

the rlax package has some packaging issues that includes a requirements and examples folder which was not supposed to be packaged. Also it is declared as a namespace package. I have reached out to the project maintainer for a [fix](https://github.com/google-deepmind/rlax/issues/133). Still, I don't think PDM should fail to install the package.

## Expected behavior

I expect installing rlax to succeed.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.10.0
Python Interpreter:
  /home/yicheng/projects/pdm-example/.venv/bin/python (3.10)
Project Root:
  /home/yicheng/projects/pdm-example
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.10.13",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.0-87-generic",
  "platform_system": "Linux",
  "platform_version": "#97~20.04.1-Ubuntu SMP Thu Oct 5 08:25:28 UTC 2023",
  "python_full_version": "3.10.13",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```
