### ISSUE TITLE
Scripts call an asynchronous method

### ISSUE THREAD

**Issue by sytranvn** [pdm-project/pdm#2364]
## Is your feature request related to a problem? Please describe.
```py
async def main():
  await asyncio.sleep(1)
  print("Hello")

if __name__ == "__main__":
  asyncio.run(main())
```
I have a script like so, and want to add it to my `pdm.scripts` 

```toml
[tool.pdm.scripts]
worker = { call = "mymodule:main" }
```
but fail because `main` is never awaited. To be able to 
call it, I need to create another wrapper method.

## Describe the solution you'd like
We can detect a method is a coroutine and await for it.
