### ISSUE TITLE
Running a PDM script named "lock" triggers `pre_lock` and `post_lock`

### ISSUE THREAD

**Issue by khanfluence** [pdm-project/pdm#2387]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

1. Add `lock` and `pre_lock`/`post_lock` PDM scripts to `pyproject.toml`:

   ```toml
   [tool.pdm.scripts]
   pre_lock = "echo pre_lock"
   post_lock = "echo post_lock"
   lock = "echo 'not really locking'"
   ```

2. Run `pdm run lock`:

   ```console
   > pdm -v run lock
   pre_lock
   not really locking
   post_lock
   ```

## Actual behavior

`pre_lock` and `post_lock` run when `pdm run lock` runs.

## Expected behavior

`pre_lock` and `post_lock` do not run. They only run when `pdm lock` runs.

## Environment Information

```bash
PDM version:
  2.10.1
Python Interpreter:
  /tmp/pdm-example/.venv/bin/python (3.9)
Project Root:
  /tmp/pdm-example
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.9.16",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "4.18.0-477.10.1.el8_8.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Wed Apr 5 13:35:01 EDT 2023",
  "python_full_version": "3.9.16",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```
