### ISSUE TITLE
`pdm venv create` does not default to `venv.location` when `.venv` exists.

### ISSUE THREAD

**Issue by laenan8466** [pdm-project/pdm#2395]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

1) **Project creation**
  ```bash
  pdm init # Create a new project
  ```
  
  with parameters resulting in this `pyproject.toml`:
  ```toml
  [project]
  name = ""
  version = ""
  description = ""
  authors = [
      {name = "", email = ""},
  ]
  dependencies = []
  requires-python = ">=3.10"
  readme = "README.md"
  license = {text = "MIT"}
  ```
  
  and creating a new `venv` with the `pyenv` global setting on `3.11` during the init command.

2) **2nd venv**
  Now creating another venv:
  
  ```bash
  pdm venv create -v 3.10
  ```

## Actual behavior

```console
STATUS: Creating virtualenv using virtualenv...
[VirtualenvCreateError]: The location /path/to/project/.venv is not empty, add --force to overwrite it.
```

No creation of 2nd `venv`.

## Expected behavior

I would have expected `pdm` to create the 2nd `venv` in `venv.location`, like described [in the documentation](https://pdm-project.org/latest/usage/venv/#the-location-of-virtualenvs). 

## Environment Information

```bash
PDM version:
  2.10.1
Python Interpreter:
  /path/to/project/.venv/bin/python (3.11)
Project Root:
  /path/to/project
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.6",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.90.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Fri Jan 27 02:56:13 UTC 2023",
  "python_full_version": "3.11.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```
