### ISSUE TITLE
Simplify defining composite scripts using arrays

### ISSUE THREAD

**Issue by OmerFI** [pdm-project/pdm#2405]
## Is your feature request related to a problem? Please describe.

PDM supports composite scripts in a way like this:
```toml
[tool.pdm.scripts]
lint = "flake8"
test = "pytest"
all = {composite = ["lint", "test"]}
```

## Describe the solution you'd like

This can be simplified using a array like [hatchling](https://hatch.pypa.io/latest/config/environment/overview/#scripts) does

```toml
[tool.pdm.scripts]
lint = "flake8"
test = "pytest"
all = ["lint", "test"]
```
