### ISSUE TITLE
Link collection ignores package-index-binding

### ISSUE THREAD

**Issue by sanmai-NL** [pdm-project/pdm#2442]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

`pyproject.toml`
```toml
...

[[tool.pdm.source]]
exclude_packages = ["*"]
include_packages = ["mypackage"]
name = "mypackage"
url = "https://gitlab.com/api/v4/projects/123456/packages/pypi/simple"

...
```

## Actual behavior

```console
$ pdm list --graph --resolve
STATUS: Fetching hashes for resolved packages...
Failed to collect links from https://pypi.org/simple/mypackage/: Client Error(404): Not Found
Failed to collect links from https://gitlab.com/api/v4/projects/123456/packages/pypi/simple/python-dotenv/: Client Error(404): Not Found
Failed to collect links from https://gitlab.com/api/v4/projects/123456/packages/pypi/simple/bandit/: Client Error(404): Not Found
Failed to collect links from https://gitlab.com/api/v4/projects/123456/packages/pypi/simple/black/: Client Error(404): Not Found
Failed to collect links from https://gitlab.com/api/v4/projects/123456/packages/pypi/simple/coverage/: Client Error(404): Not Found
Failed to collect links from https://gitlab.com/api/v4/projects/123456/packages/pypi/simple/creosote/: Client Error(404): Not Found
Failed to collect links from https://gitlab.com/api/v4/projects/123456/packages/pypi/simple/debugpy/: Client Error(404): Not Found
Failed to collect links from https://gitlab.com/api/v4/projects/123456/packages/pypi/simple/isort/: Client Error(404): Not Found
Failed to collect links from https://gitlab.com/api/v4/projects/123456/packages/pypi/simple/linkify-it-py/: Client E
...
```

## Expected behavior

No links are collected for package, index pairs that are excluded by the project config.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
  pdm info && pdm info --env
PDM version:
  2.10.4
Python Interpreter:
  /blah/.venv/bin/python (3.11)
Project Root:
  /blah
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.6",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.1.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020",
  "python_full_version": "3.11.6",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "darwin"
}
```

**Comment by frostming** [comment]
Can't reproduce here:
```toml
[project]                                                                                                                                     
name = ""                                                                                                                                     
version = ""                                                                                                                                  
description = ""                                                                                                                              
authors = [                                                                                                                                   
    {name = "Frost Ming", email = "me@frostming.com"},                                                                                        
]                                                                                                                                             
dependencies = [                                                                                                                              
    "click>=8.1.7",                                                                                                                           
    "mypackage>=0.1.0",                                                                                                                       
]                                                                                                                                             
requires-python = ">=3.11"                                                                                                                    
readme = "README.md"                                                                                                                          
license = {text = "MIT"}                                                                                                                      
                                                                                                                                              
[[tool.pdm.source]]                                                                                                                           
name = "local"                                                                                                                                
url = "http://localhost:8080/simple"                                                                                                          
verify_ssl = false                                                                                                                            
include_packages = ["mypackage"]                                                                                                              
exclude_packages = ["*"]
```

Output:
```
$ pdm list --graph --resolve -v
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
click 8.1.7 [ required: >=8.1.7 ]
mypackage 0.1.0 [ required: >=0.1.0 ]
```
