### ISSUE TITLE
 Environment variable substitution in `cmd` scripts

### ISSUE THREAD

**Issue by dbohdan** [pdm-project/pdm#2542]
## Is your feature/enhancement proposal related to a problem? Please describe.

When I tried migrating a project's tasks from [Poe the Poet](https://poethepoet.natn.io), an independent task runner for Poetry, I ran into a feature that is important to me missing.

Poe can substitute environment variables in `cmd` tasks, which are like PDM `cmd` scripts. Here is an example of how I use it:

```toml
[tool.poe.env]
"PYTHON_SOURCES" = "src tests"

[tool.poe.tasks.format]
cmd = "ruff format ${PYTHON_SOURCES}"
help = "Run the Ruff formatter"

[tool.poe.tasks.lint]
cmd = "ruff check ${PYTHON_SOURCES}"
help = "Run Ruff"
```

I find this useful because it allows you to avoid repeating yourself without invoking an external shell. Why `shell` scripts aren't a sufficient alternative: the shell depends on the platform. On Windows this is still `cmd.exe`, which has an incompatible syntax for variable substitution.

## Describe the solution you'd like

I would like to be able to substitute environment variables as `{env:PYTHON_SOURCES}` or something similar consistent with existing PDM syntax (`{args}` and `{pdm}`) in `cmd` scripts.

**Comment by frostming** [comment]
Currently `"ruff check ${PYTHON_SOURCES}"` also works in PDM `cmd`, doesn't it work for you?

**Comment by dbohdan** [comment]
﻿No. Here is a demo of what doesn't work for me.

```none
> cat pyproject.toml
[project]
name = "pdm-test"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "D. Bohdan", email = "dbohdan@dbohdan.com"},
]
dependencies = []
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
package-type = "application"

[tool.pdm.scripts]
_.env = { PYTHON_SOURCES = "test.py" }

foo.shell = "python ${PYTHON_SOURCES}"
bar.cmd = "python ${PYTHON_SOURCES}"

> cat test.py
print("Hello")

> pdm run foo
Hello

> pdm run bar
/home/dbohdan/.local/share/pdm/venvs/pdm-test-q1q4PxnD-3.11/bin/python: can't open file '/tmp/pdm-test/${PYTHON_SOURCES}': [Errno 2] No such file or directory

> pdm --version
PDM, version 2.11.2
```

**Comment by frostming** [comment]
> No. Here is a demo of what doesn't work for me.

Okay, the problem is `_.env` isn't loaded into the current process, but only takes effect in the subprocess

**Comment by dbohdan** [comment]
The scripts also succeed/fail the same  way with

```toml
[tool.pdm.scripts]
foo.shell = "python ${PYTHON_SOURCES}"
foo.env = { PYTHON_SOURCES = "test.py" }

bar.cmd = "python ${PYTHON_SOURCES}"
bar.env = { PYTHON_SOURCES = "test.py" }
```
