### ISSUE TITLE
"400 Client Error: '2.2' is an invalid value for Metadata-Version. Error: Use a known metadata version" error when running `pdm publish` on a project with a dynamic version

### ISSUE THREAD

**Issue by DetachHead** [pdm-project/pdm#2561]
- [X] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. create a project with a dynamic version, eg.
   ```toml
   [tool.pdm.version]
   source = "file"
   path = "__version__.py"

   [project]
   dynamic = ["version"]
   ```
2. run `./pw pdm publish`

## Actual behavior

```
[PublishError]: 400 Client Error: '2.2' is an invalid value for Metadata-Version. Error: Use a known metadata version. See https://packaging.python.org/specifications/core-metadata for more information. for url: https://upload.pypi.org/legacy/
```

## Expected behavior

no error. the `Metadata-Version` is generated by pdm when it built the package, and 2.2 is a valid version (seems to only be set to 2.2 when using a dynamic version. see https://github.com/pdm-project/pdm-backend/blob/ad7de0985c209136d70d19d76e1325dbcc502eb8/src/pdm/backend/_vendor/pyproject_metadata/__init__.py#L267)

**Comment by frostming** [comment]
Please explicitly specify [pdm-backend](https://pdm-project.org/latest/reference/build/) as the build backend, or it will fallback to using `setuptools`, which doesn't understand the build config as above.

**Comment by DetachHead** [comment]
@frostming sorry i didn't know that part was relevant but i did have this in my pyproject.toml already. i've updated the issue to include it

```toml
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
```
can this issue be re-opened please?
