### ISSUE TITLE
`package-type` fixer won't update toml properly for "Nested Section Ordering Issue in TOML"

### ISSUE THREAD

**Issue by wey-gu** [pdm-project/pdm#2577]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

- Say we have such pyproject.toml

```toml
[tool.pdm.version]
source = "file"
path = "src/temp/__init__.py"

[tool.pdm]
package-type = "application"

[tool.pdm.dev-dependencies]
dev = [
    "black>=23.12.1"
]
```

- Run fix with

```bash
pdm fix package-type
```

## Actual behavior

- got empty duplicated section left between its children

```toml
[tool.pdm]
distribution = "false"
[tool.pdm.version]
source = "file"
path = "src/temp/__init__.py"

[tool.pdm]  #<------ here

[tool.pdm.dev-dependencies]
dev = [
    "black>=23.12.1"
]
```

## Expected behavior

```toml
[tool.pdm]
distribution = "false"
[tool.pdm.version]
source = "file"
path = "src/temp/__init__.py"

[tool.pdm.dev-dependencies]

dev = [
    "black>=23.12.1"
]
```

## Environment Information

```bash
WARNING: The following problems are found in your project:
  package-type: package-type = "application" has been renamed to distribution = false under [tool.pdm\] table
Run pdm fix to fix all or pdm fix <name> to fix individual problem.
PDM version:
  2.12.1
Python Interpreter:
  /home/w/.local/share/pdm/venv/bin/python (3.8)
Project Root:
  /home/w/dev/pdm/temp
Local Packages:
  
WARNING: The following problems are found in your project:
  package-type: package-type = "application" has been renamed to distribution = false under [tool.pdm\] table
Run pdm fix to fix all or pdm fix <name> to fix individual problem.
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.4.0-166-generic",
  "platform_system": "Linux",
  "platform_version": "#183-Ubuntu SMP Mon Oct 2 11:28:33 UTC 2023",
  "python_full_version": "3.8.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

> I have pr to fix it :) via #2578
