### ISSUE TITLE
How to force install specific version with pdm?

### ISSUE THREAD

**Issue by FixFlare** [pdm-project/pdm#2586]
## Is your feature/enhancement proposal related to a problem? Please describe.

I'm trying to install the latest version of pydantic (2.5.3 as of writing) but I have an upstream package that has this bogus constraint:

```
[tool.poetry.dependencies]
pydantic = {extras = ["dotenv"], version = "^1.10.2"}
```

How can I force install the later version 2.5.3 with PDM? I can force install it with pip but for the life of me I can't figure out how to do it with pdm.

I tried adding this override to my pyproject.toml file:

```
[tool.pdm.resolution.overrides]
pydantic = "2.5.3"
```

This does cause pdm to attempt to install the 2.5.3 version, but it still fails out with this error:

`[InconsistentCandidate]: Provided candidate <Candidate pydantic@2.5.3 from https://pypi.org/simple/pydantic/> does not satisfy NamedRequirement(name='pydantic', marker=None, extras={'dotenv'}, specifier=<SpecifierSet('<2.0.0,>=1.10.2')>, editable=False, prerelease=None, groups=[])`

I don't think --unconstrained is meant to solve this, I thought overrides was correct?

Any help would be greatly appreciated.

Thanks,

**Comment by frostming** [comment]
`resolution.overrides` was correct, tested without problem with the following config:

```toml
[project]
dependencies = [
    "ray[default]==2.7.2",
]

[tool.pdm.resolution.overrides]
pydantic = "2.5.2"
```

**Comment by FixFlare** [comment]
@frostming 

Thanks for the quick reply. At least I know I was doing things correctly now.

I went and did a pdm init on a new project and sure enough, your example worked. I had to take dependencies out 1 at a time until I found the break.


Here is an example that I think will demonstrate the problem:

```toml
[project]
name = "python_test"
version = "0.1.0"
description = "test debug"
authors = [{ name = "FixFlare", email = "donotreply@none.com" }]
dependencies = [
    "spacy",
    "pii-codex[detections]",
]
requires-python = ">=3.10,<3.11"

[tool.pdm]
distribution = false

[[tool.pdm.source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.resolution.overrides]
pydantic = "2.5.3"
```


If you try to install these independently it works, only with them combined in the dependencies array does the problem happen.


If I had to guess, [detections] includes spacy, so I think there may be a conflict happening there.
