### ISSUE TITLE
Precedence of extra markers leads to incorrect dependencies

### ISSUE THREAD

**Issue by charliermarsh** [pdm-project/pdm#2591]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

Given a `pyproject.toml` like:

```toml
[project]
name = "black"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Charlie Marsh", email = "charlie@astral.sh"},
]
dependencies = []
requires-python = ">=3.11,<3.13"
license = {text = "MIT"}

[project.optional-dependencies]
colorama = ["colorama>=0.4.3"]
uvloop = ["uvloop>=0.15.2"]
d = [
  "aiohttp>=3.7.4; sys_platform != 'win32' or implementation_name != 'pypy'",
  "aiohttp>=3.7.4, !=3.9.0; sys_platform == 'win32' and implementation_name == 'pypy'",
]
jupyter = [
  "ipython>=7.8.0",
  "tokenize-rt>=3.2.0",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
package-type = "library"
```

Running `pip install -e .` will install `aitohttp`, even though it's an optional dependency.

Looking at the generated metadata, it seems to generate:

```
Requires-Dist: aiohttp>=3.7.4; sys_platform != "win32" or implementation_name != "pypy" and extra == "d"
```

I think this isn't quite right due to precedence -- this gets interpreted as:

```
Requires-Dist: aiohttp>=3.7.4; sys_platform != "win32" or (implementation_name != "pypy" and extra == "d")
```

So the dependency is now included on all non-`win32` platforms.

For comparison, Flit generates:

```
Requires-Dist: aiohttp>=3.7.4 ; extra == "d" and ( sys_platform != 'win32' or implementation_name != 'pypy')
```

## Environment Information

```bash
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.0",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.2.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:05 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6031",
  "python_full_version": "3.12.0",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "darwin"
}
```
