### ISSUE TITLE
Failed to resolve jaxlib

### ISSUE THREAD

**Issue by messense** [pdm-project/pdm#2600]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

Kinda duplicate with https://github.com/pdm-project/pdm/issues/2369#issuecomment-1798558375 but the issue was closed

## Steps to reproduce

`pyproject.toml`:

```toml
[tool.pdm]
[tool.pdm.dev-dependencies]
jax = [
    "jaxlib[cuda12-pip]>=0.4.23+cuda12.cudnn89",
    "jax[cuda12-pip]<1.0.0,>=0.4.23",
]

[tool.pdm.build]
includes = []

[[tool.pdm.source]]
name = "jax-releases"
url = "https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"
verify_ssl = true

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[project]
authors = []
requires-python = ">=3.10,<4.0"
dependencies = [
    "ruff<1.0.0,>=0.1.15",
]
name = "repro"
version = "0.1.0"
description = ""
readme = "README.md"
```

run `pdm lock`

## Actual behavior

```bash
pdm lock
INFO: Virtualenv /tmp/test/repro/.venv is reused.
/home/ubuntu/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/models/requirements.py:485: FutureWarning: Local version label can only be used with `==` or `!=` operators
  pkg_req = parse_as_pkg_requirement(line)
🔒 Lock failed
WARNING: Unable to find a resolution for jaxlib
because of the following conflicts:
  jaxlib==0.4.23+cuda12.cudnn89 (from jax@0.4.23)
To fix this, you could loosen the dependency version constraints in pyproject.toml. See https://pdm-project.org/latest/usage/dependency/#solve-the-locking-failure for more details.
See /tmp/pdm-lock-d3tq5w0z.log for detailed debug log.
[ResolutionImpossible]: Unable to find a resolution
WARNING: Add '-v' to see the detailed traceback
```

BTW the `FutureWarning: Local version label can only be used with == or != operators` is unhelpful because it didn't point to the source of the problem.

Relevant log:

```
pdm.termui:   Adding requirement jaxlib==0.4.23+cuda12.cudnn89(from jax 0.4.23)
unearth.collector: Collecting links from https://pypi.org/simple/jaxlib/
unearth.collector: Collecting links from https://storage.googleapis.com/jax-releases/jax_cuda_releases.html/jaxlib/
unearth.auth: Found index url https://storage.googleapis.com/jax-releases/jax_cuda_releases.html/
unearth.collector: Failed to collect links from https://storage.googleapis.com/jax-releases/jax_cuda_releases.html/jaxlib/: Client Error(404): Not Found
pdm.termui:     Could not find any matching candidates.
pdm.termui:     Could not find any matching candidates even when considering pre-releases.
pdm.termui: Candidate rejected: jax@0.4.23 because it introduces a new requirement jaxlib==0.4.23+cuda12.cudnn89 that conflicts with other requirements:

pdm.termui:   Adding requirement jaxlib==0.4.23+cuda12.cudnn89(from jax 0.4.23)
unearth.collector: Collecting links from https://pypi.org/simple/jaxlib/
unearth.collector: Collecting links from https://storage.googleapis.com/jax-releases/jax_cuda_releases.html/jaxlib/
unearth.auth: Found index url https://storage.googleapis.com/jax-releases/jax_cuda_releases.html/
unearth.collector: Failed to collect links from https://storage.googleapis.com/jax-releases/jax_cuda_releases.html/jaxlib/: Client Error(404): Not Found
pdm.termui:     Could not find any matching candidates.
pdm.termui:     Could not find any matching candidates even when considering pre-releases.
pdm.termui: Candidate rejected: jax@0.4.23 because it introduces a new requirement jaxlib==0.4.23+cuda12.cudnn89 that conflicts with other requirements:

pdm.termui: Conflicts detected:
  jaxlib==0.4.23+cuda12.cudnn89 (from jax@0.4.23)
pdm.termui: Error occurs
```

## Expected behavior

Create/update `pdm.lock`.

## Environment Information

```bash
$ pdm info && pdm info --env
PDM version:
  2.12.2
Python Interpreter:
  /tmp/test/repro/.venv/bin/python (3.10)
Project Root:
  /tmp/test/repro
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.10.12",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.19.0-1029-aws",
  "platform_system": "Linux",
  "platform_version": "#30~22.04.1-Ubuntu SMP Thu Jul 13 17:17:32 UTC 2023",
  "python_full_version": "3.10.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}
```
