### ISSUE TITLE
Support of Dependency Groups in `pyproject.toml` | PEP 735

### ISSUE THREAD

**Issue by ioangatop** [pdm-project/pdm#2701]
## Is your feature/enhancement proposal related to a problem? Please describe.

Hi!

First of all, thank you for developing and maintaining this awesome library!

I would like to ask if you could support dependency groups in `pyproject.toml` - [PEP 735](https://peps.python.org/pep-0735/)

## Describe the solution you'd like

To be able to merge groups and form a new one, as follows:

```toml
[tool.pdm.dev-dependencies]
test = ["pytest", "coverage"]
docs = ["sphinx", "sphinx-rtd-theme"]
typing = ["mypy", "types-requests"]

[dependency-groups]
typing-test = [{include = "typing"}, {include = "test"}]
dev = [{include = "test"}, {include = "docs"}, {include = "typing"}]
all = [{include = "test"}, {include = "docs"}, {include = "typing"}, "useful-something"]
```
