### ISSUE TITLE
Installing "PySide6" with PDM 2.13.0 on Windows fails

### ISSUE THREAD

**Issue by p-rogalski** [pdm-project/pdm#2730]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Use newest PDM (`2.13.0`)
2. Use following minimal `pyproject.toml`:
   
   ```toml
   [build-system]
   requires = ["pdm-backend"]
   build-backend = "pdm.backend"

   [project]
   name = "pyside6_test"
   version = "0.1.0"
   dependencies = ["PySide6"]
   requires-python = ">=3.11,<3.13"
   ```

3. Execute `pdm install`
4. Install fails, see debug log:

    [pdm-install-7832bnox.log](https://github.com/pdm-project/pdm/files/14787732/pdm-install-7832bnox.log)

## Actual behavior

The dependency packages `pyside6-essentials` and `pyside6-addons` are failing to install. However, with PDM `2.12.4` the packages install correctly. 

I suspect that the packages are not downloaded correctly in the latest PDM version because they are relatively huge (75 MB and 105 MB).

## Expected behavior

All packages should install correctly.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PS C:\Users\progalski\git\pyside6_test> pdm info && pdm info --env
PDM version:
  2.13.0
Python Interpreter:
  C:\Users\progalski\git\pyside6_test\.venv\Scripts\python.exe (3.11)
Project Root:
  C:/Users/progalski/git/pyside6_test
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.11.4",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.22631",
  "python_full_version": "3.11.4",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "win32"
}
```
