### ISSUE TITLE
Different indexes for different groups

### ISSUE THREAD

**Issue by Paillat-dev** [pdm-project/pdm#2834]
## Is your feature/enhancement proposal related to a problem? Please describe.

I would like to be able to install my project, which uses pytorch in one command with disregard of my environment. However, torch for cuda is on pytorch's indexes whilst the cpu version is on pypi's.

## Describe the solution you'd like

Something like:
```toml
[project.optional-dependencies]
cuda11_8 = [{version = "2.2.0", index = "https://download.pytorch.org/whl/cu118"}]
```
