### ISSUE TITLE
OS Specific Scripts

### ISSUE THREAD

**Issue by ameily** [pdm-project/pdm#2848]
## Is your feature/enhancement proposal related to a problem? Please describe.

I have a Python project that runs on both Windows and Linux. I have a `lint` PDM script that runs pylint. The problem is that I need to ignore Windows-specific source files when running on Linux and ignore Linux-specific source files when running on Windows. I have what I consider a HACK that works:

```toml
[tool.pdm.scripts]
# This is ugly but runs the correct lint command based on the OS. This check works on both Windows
# and Linux
lint = {shell = "(python -c \"import sys;import platform;sys.exit(1 if any(platform.win32_ver()) else 0)\" && {pdm} run lint-linux) || {pdm} run lint-windows" }

lint-windows = "pylint --ignore '[LINUX_SPECIFIC_SOURCE_FILES]' my_project"
lint-linux = "pylint --ignore '[WINDOWS_SPECIFIC_SOURCE_FILES]' my_project"
```

## Describe the solution you'd like

I assume there's a better way to do what I need. If not, I think a new script type that selects the script to run based on the OS. Something like:

```toml
[tool.pdm.scripts]
lint = { os_match = { win32 = "lint-windows", linux = "lint-linux" } }

lint-windows = "pylint --ignore '[LINUX_SPECIFIC_SOURCE_FILES]' my_project"
lint-linux = "pylint --ignore '[WINDOWS_SPECIFIC_SOURCE_FILES]' my_project"
```

Looking at [`TaskRunner.run_task`](https://github.com/pdm-project/pdm/blob/main/src/pdm/cli/commands/run.py#L233), I think we would add a new `kind` that behaves something like:

```python
if kind == "os_match":
    assert isinstance(value, dict)
    if sys.platform.startswith("linux") and "linux" in value:
        # generic linux
        script = value["linux"]
    else:
        # match the platform exactly
        script = value[sys.platform]
    
    self.run(...)
```
