### ISSUE TITLE
Sync package version between `dependencies` and `build-system.requires`

### ISSUE THREAD

**Issue by siddancha** [pdm-project/pdm#2863]
I have the following use case, which is quite common in deep learning workflows:

- `setup.py` to build PyTorch C++/CUDA extensions [[1](https://github.com/pytorch/extension-cpp), [2](https://pytorch.org/tutorials/advanced/cpp_extension.html)]:
```python
from setuptools import setup
from torch.utils.cpp_extension import BuildExtension, CUDAExtension, CppExtension

setup(
    ext_modules=[
        CUDAExtension(...),
        CppExtension(...),
    ],
    cmdclass={
        'build_ext': BuildExtension
    }
)
```

- `pyproject.toml` to build these extensions:
```toml
[project]
name = "mylibrary"
dependencies = [
    "torch",  # torch in dependencies
    "torchmetrics",
    "torchvision",
    ...
]
requires-python = ">=3.8"

[build-system]
requires = ["setuptools", "wheel", "torch"]  # torch in build-system-requires
build-backend = "setuptools.build_meta"
```

The issue is when doing `pdm install` (or even `pip install`) with isolation, two separate versions of torch might be used for building the extension and as a dependency for the package, which can lead to runtime errors.

Is there a way to tell PDM that the two torch versions should be identical? Thanks!

**Comment by frostming** [comment]
--no-isolation

**Comment by frostming** [comment]
just no

**Comment by pawamoy** [comment]
> Is there a way to tell PDM that the two torch versions should be identical? Thanks!

Best effort is to provide the same requirements:

```toml
[project]
name = "mylibrary"
dependencies = [
    "torch>=x.y.z",
    "torchmetrics",
    "torchvision",
    ...
]
requires-python = ">=3.8"

[build-system]
requires = ["setuptools", "wheel", "torch>=x.y.z"]
build-backend = "setuptools.build_meta"
```

It's a "best-effort" because it cannot ensure the exact same versions will be used when building and when installing, since this could happen on different systems, and different requirements.

**Comment by SealedServant** [comment]
> Is there any way to do this without `--no-isolation`? `--no-isolation` for me opens another can of worms.

You can add extra options passed to individual `pdm` commands by `tool.pdm.options` configuration:

```toml
[tool.pdm.options]
add = ["--no-isolation"]
install = ["--no-isolation"]
```
