### ISSUE TITLE
Download progress was not shown with large package installation

### ISSUE THREAD

**Issue by ewfian** [pdm-project/pdm#2878]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Thank you for creating this great project, I love pdm but it always bothers me when I install packages,

I noticed that [this PR](https://github.com/pdm-project/pdm/pull/2328) added a download progress. When installing some small packages, I did observe that the progress was working, but when installing a large package, the progress is not displayed during the download, and 100% is displayed at the moment the download is completed.

![image](https://github.com/pdm-project/pdm/assets/12423122/2595c47f-19fb-40d2-b1f9-f7789d329438)
![image](https://github.com/pdm-project/pdm/assets/12423122/cbbe088c-0eac-4424-a620-1c4d8f55a35f)

```toml
dependencies = [
    "spacy>=3.7.4",
    "ja_core_news_lg @ https://github.com/explosion/spacy-models/releases/download/ja_core_news_lg-3.7.0/ja_core_news_lg-3.7.0-py3-none-any.whl",
    "fugashi[unidic-lite]>=1.3.2",
    "sentence-transformers>=2.7.0",
    "torch>=2.3.0",
]
[[tool.pdm.source]]
url = "https://download.pytorch.org/whl/cu118"
verify_ssl = true
name = "torch"
include_packages = ["torch"]
```

## Actual behavior
The progress is not displayed during the download, and 100% is displayed at the moment the download is completed.

## Expected behavior
Progress is displayed correctly during the download process

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:
  2.15.1    
Python Interpreter:
  C:\Users\ewfian\***\.venv\Scripts\python.exe (3.12)
Project Root:
  C:/Users/ewfian/***
Local Packages:
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.3",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19045",
  "python_full_version": "3.12.3",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "win32"
}
```

Poetry can accurately report the download progress. I really hope that pdm can also improve this.
