### ISSUE TITLE
feature: allow array of commands in scripts

### ISSUE THREAD

**Issue by Goldziher** [pdm-project/pdm#2985]
## Is your feature/enhancement proposal related to a problem? Please describe.

Currently the following is not possible:

```toml
[tool.pdm.scripts]
post_install = "pre-commit install && pre-commit install --hook-type commit-msg && pre-commit install --install-hooks"
```

The workaround is to do something like this:

```toml
[tool.pdm.scripts]
pre_setup_pre_commit = "pre-commit install --hook-type commit-msg"
setup_pre_commit = "pre-commit install"
post_setup_pre_commit = "pre-commit install --install-hooks"
post_install = "pdm run setup_pre_commit"
```

Or create a script file and call it.

## Describe the solution you'd like

I would like to have an ability to do the following:

or alternatively like the following

```toml
[tool.pdm.scripts]
post_install = ["pre-commit install", "pre-commit install --hook-type commit-msg", "pre-commit install --install-hooks"]
```

```toml
[tool.pdm.scripts]
post_install = ["pre-commit", "install", "&&", "pre-commit", "install", "--hook-type", "commit-msg", "&&", "pre-commit", "install", "--install-hooks"]
```
