### ISSUE TITLE
Allow to disable default PyPI without overriding it

### ISSUE THREAD

**Issue by aleksul** [pdm-project/pdm#3052]
## Is your feature/enhancement proposal related to a problem? Please describe.

Currently, if one wants to:

- use their own package registry 
- with credentials from global config/keyring (i.e., those credentials are named to be used only for `my-private-registry`)
- and don't want to allow PyPI as fallback, 

the following setup is needed:

```toml
[tool.pdm.resolution]
respect-source-order = true

[[tool.pdm.source]]
name = "my-private-registry"
url = "https://my-private-registry.com/simple"

[[tool.pdm.source]]
name = "pypi"
url = "intentionally-incorrect-url"
```

Problem is, if PDM fails to get credentials for `my-private-registry`, it will try to use the next available source, and when it finally fails, the displayed error will be:

```
[ValueError]: Invalid find link or non-existing path: intentionally-incorrect-url/some-package
```

...which I find misleading and unhelpful, especially in CI environments.

## Describe the solution you'd like

A config flag, which allows to disable pypi entirely, for example:

```toml
[tool.pdm.resolution]
disable-pypi = true
```

OR

```toml
[[tool.pdm.source]]
name = "pypi"
disabled = true
```

Therefore, the error, which will be raised if no credentials were found, will be:

```
[PdmException]: The credentials for my-private-registry.com are not provided. To give them via interactive shell, please rerun the command with `-v` option.
```
