### ISSUE TITLE
[bug] inherit_metadata would be written in lock file if the file is not pdm.lock even strategy config is true

### ISSUE THREAD

**Issue by monchin** [pdm-project/pdm#3232]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. Init a pdm project with `pyproject.toml` 
```toml
[project]
name = "pdm_test"
version = "0.1.0"
description = "test"
authors = [
    {name = "mon", email = "fake@email.com"},
]
dependencies = [
    "numpy>=2.0.0"
]
requires-python = "==3.10.*"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
distribution = false
```

2. In this project, run `pdm config strategy.inherit_metadata false`, and ensure with `pdm config strategy.inherit_metadata`
3. Run `pdm lock -L pdm.test.lock`

## Actual behavior

`pdm.test.lock`'s strategy would be `strategy = ["inherit_metadata"]`

## Expected behavior

`pdm.test.lock`'s strategy should be `strategy = []`

## Environment Information

pdm 2.19.3

I found that in [this line](https://github.com/pdm-project/pdm/blob/2.19.3/src/pdm/project/core.py#L133), it actually  would not be run if we set `-L pdm.test.lock`, so maybe it should be run regardless of `if self._lockfile is None`?
