### ISSUE TITLE
[bug] use_uv setting invalid in pre_lock

### ISSUE THREAD

**Issue by monchin** [pdm-project/pdm#3256]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

In `pyproject.toml` `[tool.pdm.scripts]`, add these lines
```toml
[tool.pdm.scripts]
pre_lock = "pdm config use_uv false"
post_lock = "pdm config use_uv true"
```
run `pdm lock`

## Actual behavior

uv is still used, output
```
⠋ 0:00:00 Resolve for environment (>=3.10) None
INFO: Using uv is experimental and might break due to uv updates.
Resolved 74 packages in 4.40s
Changes are written to pdm.lock.
  0:00:04 🔒 Lock successful.
```
and `pdm.lock` doesn't include groups information in packages.
## Expected behavior
uv not used when run locking

## Environment Information
pdm 2.20.0.post1, windows 10

# Motivation
For some projects, I need to get groups information for every dependent package, but if `use_uv`  is true, groups information would be removed. So I'd like to make a hook pre and post lock to set `use_uv` false and true respectively.

# Reason Analysis
I found that `pdm Project` reads the global config at the very first, and then combines it with local config  and caches the whole config. So even `pre_lock` sets `use_uv` to false, `use_uv` in config would always be true.

To solve this issue, what about offer a method `refresh_global_config` and run it before judging whether `use_uv` is true, and use `project.global_config.get("use_uv")` instead of `project.config.get("use_uv")`?

**Comment by frostming** [comment]
Sorry I don't understand, `project.config` always responds to the latest changes: https://github.com/pdm-project/pdm/blob/acb40b0713c30466dcbab73e6b98d1add8e5dd98/src/pdm/project/core.py#L221

**Comment by frostming** [comment]
Hi, according to the current situation, I would recommend using an in-project pdm plugin. Here is how to do it:

```python
# plugin/my_plugin.py
def plugin(core):
    from pdm.signals import pre_lock, post_lock
    
    @pre_lock.connect
    def disable_uv(project, *args, **kwargs):
        project.project_config["use_uv"] = false

    @post_lock.connect
    def enable_uv(project, *args, **kwargs):
        project.project_config["use_uv"] = true
```
```toml
# plugin/pyproject.toml
[project]
name = "my_plugin"
version = "0.0.0"

[project.entry-points.pdm]
no_uv = "my_plugin:plugin"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
```
```toml
# pyproject.toml
...
[tool.pdm]
plugins = [
    "-e file:///${PROJECT_ROOT}/plugin"
]
```
