### ISSUE TITLE
pdm update --unconstrained fails to preserve style in [dependency-groups]

### ISSUE THREAD

**Issue by russellane** [pdm-project/pdm#3258]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

Begin with `pyproject.toml` with outdated dependencies:

```toml
[project]
name = "testpkg"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = []

[tool.pdm.dev-dependencies]
dev = [
    "black==24.8.0",
    "flake8==7.1.0",
    "isort==5.13.1",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

# vim: set ts=4 sw=4 et:
```

## Actual behavior

The `tool.pdm.dev-dependencies` section is renamed, reformatted and relocated to the end of the file.

```toml
[project]
name = "testpkg"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

# vim: set ts=4 sw=4 et:

[dependency-groups]
dev = ["black>=24.10.0", "flake8>=7.1.1", "isort>=5.13.2"]
```
## Another step to reproduce

I renamed `tool.pdm.dev-dependencies` to `dependency-groups` before running update --unconstrained; the deps are reformatted, and a `[tool.pdm]` section is appended.

## Actual behavior

```toml
[project]
name = "testpkg"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = ["black>=24.10.0", "flake8>=7.1.1", "isort>=5.13.2"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

# vim: set ts=4 sw=4 et:

[tool.pdm]
```

## Expected behavior

Expected formatting-style to be preserved, as with pdm-2.19.3.

```toml
[project]
name = "testpkg"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = []

[tool.pdm.dev-dependencies]
dev = [
    "black>=24.10.0",
    "flake8>=7.1.1",
    "isort>=5.13.2",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

# vim: set ts=4 sw=4 et:
```

## Environment Information

```bash
PDM version:
  2.20.0.post1
Python Interpreter:
  /opt/homebrew/Cellar/python@3.10/3.10.14_1/libexec/bin/python (3.10)
Project Root:
  /Users/russe/dev/testpkg
Local Packages:
  /Users/russe/dev/testpkg/__pypackages__/3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.13.0",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "23.6.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:04 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6020",
  "python_full_version": "3.10.14",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```
