### ISSUE TITLE
[bug] `pdm install --plugins` would fail when use_uv enabled

### ISSUE THREAD

**Issue by monchin** [pdm-project/pdm#3283]
### Describe the bug

If `use_uv` is enabled, `pdm install --plugins` would only mkdir `.pdm-plugins` and create a `.gitignore` without `Lib`

### To reproduce

In one pdm project, create `plugin/my_plugin.py`
```python
# plugin/my_plugin.py`
def plugin(core):
    print("test")
```
and `plugin/pyproject.toml`
```toml
# plugin/pyproject.toml
[project]
name = "my_plugin"
version = "0.0.0"

[project.entry-points.pdm]
test_plug = "my_plugin:plugin"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
```
In `pyproject.toml`, add
```toml
[tool.pdm]
plugins = [
    "-e file:///${PROJECT_ROOT}/plugin#egg=my-plugin"
]
```
run `pdm config use_uv true` and confirm with `pdm config use_uv`, then run `pdm install --plugins`

### Expected Behavior

The dir structure would be like
```
C:\TEST-PDM\.PDM-PLUGINS
└─Lib
    └─site-packages
        └─my_plugin-0.0.0.dist-info
        └─my_plugin.pth
```

This issue is because when `use_uv` is enabled, `pdm install` would get `UvResolver`, but in this case `RLResolver` should be gotten. So if in `pdm/cli/commands/install.py`,
```python
class Command(BaseCommand):
    def install_plugins(self, project: Project) -> None:
        ...
        with project.core.ui.open_spinner("[success]Installing plugins...[/]"):
            with project.core.ui.logging("install-plugins"):
                install_requirements(
                    plugins, environment, clean=True, use_install_cache=project.config["install.cache"]
                )
```
is changed to 
```python
        with project.core.ui.open_spinner("[success]Installing plugins...[/]"):
            with project.core.ui.logging("install-plugins"):
                if project.config.get("use_uv", False):
                    use_uv = True
                    project.config["use_uv"] = False
                install_requirements(
                    plugins, environment, clean=True, use_install_cache=project.config["install.cache"]
                )
                if use_uv:
                    project.config["use_uv"] = True
```
this issue would be resolved.

### Environment Information

PDM version:
  2.20.1

### Are you willing to submit a PR to fix this bug?

- [X] Yes, I would like to submit a PR.
