### ISSUE TITLE
`pdm update -u` fails when a depenendcy group contains a dependency group include

### ISSUE THREAD

**Issue by momostein** [pdm-project/pdm#3333]
### Describe the bug

Since [PEP 735](https://peps.python.org/pep-0735/) was accepted, PDM has added support for it. This PEP also came with a specification for [dependency group includes](https://peps.python.org/pep-0735/#dependency-group-include):

```toml
[dependency-groups]
group-a = ["foo"]
group-b = ["foo>1.0"]
group-c = ["foo<1.0"]
all = [
    "foo",
    {include-group = "group-a"},
    {include-group = "group-b"},
    {include-group = "group-c"},
]
```

However, when a dependency group contains such an `{include-group = "..."}` statement, PDM fails to write the changes to `pyproject.toml`.

### To reproduce

1. Run `pdm init` to create a project
2. Use the following `pyproject.toml`
   ```toml
    [project]
    name = "pdm-include-group-bug"
    version = "0.1.0"
    description = "Default template for PDM package"
    
    dependencies = []
    requires-python = "==3.12.*"
    readme = "README.md"
    license = {text = "MIT"}
    
    
    [tool.pdm]
    distribution = false
    
    [dependency-groups]
    lint = [
        "ruff>=0.8.1",
    ]
    test = [
        "pytest>=8.3.4",
        { include-group = "lint" },
    ]
    ```
3.  Run `pdm update -u`, this results in:
    ```
      0:00:05 🔒 Lock successful.
    Changes are written to pyproject.toml.
    Changes are written to pyproject.toml.
    [AttributeError]: 'InlineTable' object has no attribute 'startswith'
    WARNING: Add '-v' to see the detailed traceback
    ```

### Expected Behavior

I expected this to not fail and properly update the pyproject.toml

## `pdm info`

```
PDM version:
  2.21.0
Python Interpreter:
  C:\<PROJECT_DIR>\pdm-include-group-bug\.venv\Scripts\python.exe (3.12)
Project Root:
  C:/<PROJECT_DIR>/pdm-include-group-bug
Local Packages:
```

## `pdm info --env`

```json
{
  "implementation_name": "cpython",
  "implementation_version": "3.12.2",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19045",
  "python_full_version": "3.12.2",
  "platform_python_implementation": "CPython",
  "python_version": "3.12",
  "sys_platform": "win32"
}
```

### pdm -v output

```
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pytest
pdm.termui:   ruff
pdm.termui:   ruff
pdm.termui:   Adding requirement python==3.12.*
pdm.termui:   Adding requirement pytest
pdm.termui:   Adding requirement ruff
pdm.termui:   Adding requirement ruff
pdm.termui: ======== Starting round 0 ========
pdm.termui: Adding new pin: python None
pdm.termui: ======== Starting round 1 ========
pdm.termui:   Adding requirement colorama; sys_platform == "win32"(from pytest 8.3.4)
pdm.termui:   Adding requirement iniconfig(from pytest 8.3.4)
pdm.termui:   Adding requirement packaging(from pytest 8.3.4)
pdm.termui:   Adding requirement pluggy<2,>=1.5(from pytest 8.3.4)
pdm.termui: Adding new pin: pytest 8.3.4
pdm.termui: ======== Starting round 2 ========

## CENSORED (downloading packages from private repository)

pdm.termui: Adding new pin: ruff 0.8.1
pdm.termui: ======== Starting round 3 ========
pdm.termui: Adding new pin: pluggy 1.5.0
pdm.termui: ======== Starting round 4 ========
pdm.termui: Adding new pin: colorama 0.4.6
pdm.termui: ======== Starting round 5 ========
pdm.termui: Adding new pin: iniconfig 2.0.0
pdm.termui: ======== Starting round 6 ========
pdm.termui: Adding new pin: packaging 24.2
pdm.termui: ======== Starting round 7 ========
pdm.termui: ======== Resolution Result ========
pdm.termui:      python None
pdm.termui:      pytest 8.3.4
pdm.termui:        ruff 0.8.1
pdm.termui:      pluggy 1.5.0
pdm.termui:    colorama 0.4.6
pdm.termui:   iniconfig 2.0.0
pdm.termui:   packaging 24.2
pdm.termui: Fetching hashes for pytest@8.3.4
pdm.termui: Fetching hashes for ruff@0.8.1
Changes are written to pyproject.toml.
Changes are written to pyproject.toml.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\<USER>\appdata\roaming\python\scripts\pdm.exe\__main__.py", line 7, in <module>
  File "C:\Users\<USER>\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\core.py", line 392, in main
    return core.main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<USER>\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\core.py", line 270, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "C:\Users\<USER>\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\core.py", line 265, in main
    self.handle(project, options)
  File "C:\Users\<USER>\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\core.py", line 195, in handle
    command.handle(project, options)
  File "C:\Users\<USER>\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\cli\commands\update.py", line 75, in handle
    self.do_update(
  File "C:\Users\<USER>\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\cli\commands\update.py", line 196, in do_update
    project.add_dependencies(deps, group, selection.dev or False)
  File "C:\Users\<USER>\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\project\core.py", line 707, in add_dependencies
    parsed_deps = [parse_line(dep) for dep in deps]
                   ^^^^^^^^^^^^^^^
  File "C:\Users\<USER>\AppData\Roaming\pdm\venv\Lib\site-packages\pdm\models\requirements.py", line 482, in parse_line
    if line.startswith("-e "):
       ^^^^^^^^^^^^^^^
AttributeError: 'InlineTable' object has no attribute 'startswith'
```

### Are you willing to submit a PR to fix this bug?

- [ ] Yes, I would like to submit a PR.
