### ISSUE TITLE
pdm sync/lock/install breaks by defining private index and using keyring

### ISSUE THREAD

**Issue by farndt** [pdm-project/pdm#3334]
### Describe the bug

If I define a private index like 
```toml
[[tool.pdm.source]]
name = "remote"
url = "https://artifactory.company.com/artifactory/api/pypi/remote/simple"
verify_ssl = true
username = "user" 
password = "pass"
```
pdm sync/lock/install works as expected.

If I set up keyring in pdm: `pdm self add keyring` and now remove username and password from pyproject.toml and set credentials in Windows Credential Manager:
service: pdm-pypi-remote
username: user
password: pass

I will get:
```shell
unearth.collector: Failed to collect links from https://artifactory.company.com/artifactory/api/pypi/remote/simple/blinker/: Client Error(403)
pdm.exceptions.CandidateNotFound: Unable to find candidates for blinker. There may exist some issues with the package name or network condition.
``` 

In src\pdm\project\core.py breakpoint at line 502 I see that username is missing. Only password is set by src\pdm\_types.py RepositoryConfig(_RepositoryConfig) class

### To reproduce

1. `keyring set pdm-pypi-remote username` -> enter _password_
2. `pdm self add keyring`
3. define index
```toml
[[tool.pdm.source]]
name = "remote"
url = "https://artifactory.company.com/artifactory/api/pypi/remote/simple"
verify_ssl = true
```
4. `pdm sync/lock/install`

### Expected Behavior

**pdm** reads _username_ and _password_ using Keyring get_credentials service-name

This would allow teams to use keyring without making changes to pyproject.toml. Due to lack of encryption and simple logging, it should be avoided to use environment variables as storage for credentials.

### Environment Information

```shell
PDM version:
  2.21.1
Python Interpreter:
  C:\Users\me\Desktop\pdm\.venv\Scripts\python.exe (3.10)
Project Root:
  C:/Users/me/Desktop/pdm
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.10.11",
  "os_name": "nt",
  "platform_machine": "AMD64",
  "platform_release": "10",
  "platform_system": "Windows",
  "platform_version": "10.0.19045",
  "python_full_version": "3.10.11",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "win32"
}
```

### Are you willing to submit a PR to fix this bug?

- [ ] Yes, I would like to submit a PR.
