### ISSUE TITLE
pdm venv create is not handling distrobox export correctly

### ISSUE THREAD

**Issue by klmcwhirter** [pdm-project/pdm#3369]
### Describe the bug

When executing `pdm venv create -f PATH_TO_PYTHON` pattern where PATH_TO_PYTHON is a distrobox export script it fails because instead of executing it the last place in the file containing the word python is used instead. That is wrong. It should be performing --version instead.

Here is the contents of the script:
```bash
#!/bin/sh
# distrobox_binary
# name: fedora41-distrobox-quadlet
if [ -z "${CONTAINER_ID}" ]; then
        exec "/var/home/klmcw/.local/bin/distrobox-enter"  -n fedora41-distrobox-quadlet  --  '/usr/bin/python3.14'  "$@"
elif [ -n "${CONTAINER_ID}" ] && [ "${CONTAINER_ID}" != "fedora41-distrobox-quadlet" ]; then
        exec distrobox-host-exec '/var/home/klmcw/.local/bin/python3.14' "$@"
else
        exec '/usr/bin/python3.14' "$@"
fi
```

When I execute `~/.local/bin/python3.14 --version` on the host I get:
```bash
$ ~/.local/bin/python3.14 --version
Python 3.14.0a2

```

### To reproduce

1. Create a distrobox containing python3.14
1. export to ~/.local/bin
1. execute `pdm venv create -f ~/.local/bin/python3.14`

Get error that /usr/bin/python3.14 does not exist.

### Expected Behavior

Should create venv with ~/.local/bin/python3.14 as base-executable

### Environment Information

`pdm info && pdm info --env`
WARNING: Project requires a python version of ==3.14.*, The virtualenv is being created for you as it cannot be matched to the right version.
INFO: python.use_venv is on, creating a virtualenv for this project...
[VirtualenvCreateError]: Command '['/var/home/klmcw/.local/share/pdm/venv/bin/python', '-m', 'virtualenv', '/var/home/klmcw/src/soft.lan/klmcw/jfimportctl/.venv', '-p', 
'/usr/bin/python3.14', '--prompt=jfimportctl-3.14', '--no-pip', '--no-setuptools', '--no-wheel']' returned non-zero exit status 1.

### Verbose Command Output

`pdm venv create -f ~/.local/bin/python3.14 -v`
[VirtualenvCreateError]: Command '['/var/home/klmcw/.local/share/pdm/venv/bin/python', '-m', 'virtualenv', '/var/home/klmcw/src/soft.lan/klmcw/jfimportctl/.venv', '-p', 
'/usr/bin/python3.14', '--prompt=jfimportctl-3.14', '--no-pip', '--no-setuptools', '--no-wheel', '-v']' returned non-zero exit status 1.

### Additional Context

The path `/usr/bin/python3.14` indeed does not exist. But it should not be looking there.

Also, it should not be using virtualenv. It should be using venv. But that does not matter much - it got the python path wrong.

### Are you willing to submit a PR to fix this bug?

- [ ] Yes, I would like to submit a PR.

**Comment by frostming** [comment]
I have never heard of this tool and don't plan to support any arbitrary script wrappers, after all, I am only one person.

You should create your own virtual environment.
```
~/.local/bin/python3.14 -m venv .venv`
```

**Comment by klmcwhirter** [comment]
distrobox has been around for quite awhile and is the wave of the future. It is a way to minimize disk utilization on container first distros like universal blue or vanilla os.

But, making assumptions at all about an executable without interrogating it to be sure is ... How do you know that you are building a working venv otherwise?

Come on, now. You seem better than that. Don't just dismiss this so readily.

**Comment by frostming** [comment]
> Come on, now. You seem better than that. Don't just dismiss this so readily.


come on, don't push on an OSS maintainer who wrote this unpaid. you are more experienced than me on this topic. just learn the codebase and try fixing it.

**Comment by klmcwhirter** [comment]
For future readers, here is a workaround. The trick is to use `full_path/python -m venv .venv` directly because `findpython` does not detect the python interpreter correctly even though full path to it has been specified.

```toml
[tool.pdm.scripts]
# The ${HOME} env var represents any set of env vars needed to construct the path to python.
# The point is that information is encoded here and is version controlled so the venv creation is repeatable.
_create_venv.shell = "${HOME}/.local/bin/python3.14.0a3 -m venv .venv"
# This would not typically be needed. It just happens that both executables are needed for this specific project.
_create_symlinks.shell = "ln -s ${HOME}/.local/bin/python3.14.0a3t .venv/bin/python3.14.0a3t"
create.composite = ["_create_venv", "_create_symlinks"]
create.help = "Create the .venv and needed symlinks"
```
