### ISSUE TITLE
pdm can't select right dependency based on sys_platform specifier

### ISSUE THREAD

**Issue by zhukovgreen** [pdm-project/pdm#3394]
### Describe the bug

pdm can't solve the following pyproject.toml

```toml
❯ cat pyproject.toml
[project]
name = "cross-platform-torch"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "zhukovgreen", email = "iam@zhukovgreen.pro"},
]
dependencies = [
    "torch==1.13.1+cpu; sys_platform != 'darwin'",
    "torch==1.13.1; sys_platform == 'darwin'",
]
requires-python = "==3.10.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[project.optional-dependencies]

[[tool.pdm.source]]
url = "https://download.pytorch.org/whl/cpu"
verify_ssl = true
name = "torch_cpu"
```

When I am trying to do a pdm lock - it gives the lock file which has only +cpu version of torch. But when do pdm sync - it fails with pdm.exceptions.CandidateNotFound: No candidate is found for
`torch` that matches the environment or hashes. Because the target platform is Darwin and torch should not contain +cpu suffix

### To reproduce

1. Create virtualenv. pdm venv create 
2. Create pyproject.toml
```toml
[project]
name = "cross-platform-torch"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "zhukovgreen", email = "iam@zhukovgreen.pro"},
]
dependencies = [
    "torch==1.13.1+cpu; sys_platform != 'darwin'",
    "torch==1.13.1; sys_platform == 'darwin'",
]
requires-python = "==3.10.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[project.optional-dependencies]

[[tool.pdm.source]]
url = "https://download.pytorch.org/whl/cpu"
verify_ssl = true
name = "torch_cpu"
```
2. Run pdm lock
3. Run pdm sync

Also tried using "macos_arm" in the sys_platform specifier in the pyproject.toml and also tried to do pdm lock --platform=macos_arm --append. Still the same problem. pdm tries to install torch==1.13.1+cpu on my mac

### Expected Behavior

pdm properly selects torch based on the platform when doing pdm sync

### Environment Information

{
  "implementation_name": "cpython",
  "implementation_version": "3.13.1",
  "os_name": "posix",
  "platform_machine": "arm64",
  "platform_release": "24.3.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:16 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6000",
  "python_full_version": "3.10.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}

### Are you willing to submit a PR to fix this bug?

- [ ] Yes, I would like to submit a PR.
