### ISSUE TITLE
Use dev dependencies while computing a dynamic version raise ModuleNotFoundError

### ISSUE THREAD

**Issue by ifxfrancois** [pdm-project/pdm#3400]
### Describe the bug

when pdm calls the version getter the dev dependencies are not installed yet.  The getter fails when importing them.

`ModuleNotFoundError: No module named ` ...

### To reproduce

Create a pdm project with `pdm init`

replace the pyproject.toml
```toml
[project]
name = "test-dyn-version"
description = "test if version can use any dependencies"
authors = [
    {name = "me", email = "me@example.com"},
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}
dynamic = [ "version" ]
dependencies = []

[tool.pdm.version]
source = "call"
getter = "version:get_version"

[tool.pdm]
distribution = true

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.dependency-groups]
dev = [
    "gitpython>=3.1.44",
    "semver>=3.0.4",
]
```
add a version.py file at the root of the project wit folowing content:
```python
from semver import Version
from git import Git


def get_version():
    # do stuff with Git and semver
    return "0.1.2"
``` 

run any pdm command the calls the version: `pdm sync`, `pdm install`, `pdm build`

### Expected Behavior

no ModuleNotFoundError  when calling pdm command

### Environment Information

PDM version:
  2.22.3
Python Interpreter:
  /home/user/playground/python/pdm-version/.venv/bin/python (3.10)
Project Root:
  /home/user/playground/python/pdm-version
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.10.12",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.133.1-microsoft-standard-WSL2",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Thu Oct 5 21:02:42 UTC 2023",
  "python_full_version": "3.10.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "linux"
}

### Are you willing to submit a PR to fix this bug?

- [ ] Yes, I would like to submit a PR.
