### ISSUE TITLE
Cannot include project's extra dependencies into a dependency group

### ISSUE THREAD

**Issue by francis-clairicia** [pdm-project/pdm#3416]
### Describe the bug

Including extra dependency group defined in `project.optional-dependencies` to a group in `dependency-groups` via `include-group` directive does not work.

### To reproduce

Minimal reproducible example of `pyproject.toml`:
```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "my_project"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Someone", "email" = "someone@mail.com"},
]
dependencies = []
requires-python = ">=3.13"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
trio = [
    "trio>=0.26,<1",
    "outcome~=1.3",
]

[dependency-groups]
uvloop = [
    "uvloop; os_name=='posix'"
]
benchmark-servers-deps = [
    {include-group = "uvloop"},
    {include-group = "trio"},
]

[tool.pdm]
distribution = true
```

### Expected Behavior

Use optional dependencies in the same way as other development dependencies.

### Environment Information

```
PDM version:
  2.22.4
Python Interpreter:
  /home/XXX/Test/pdm-bug/.venv/bin/python (3.13)
Project Root:
  /home/XXX/Test/pdm-bug
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.13.1",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.6.75-2-MANJARO",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Mon Feb  3 17:53:46 UTC 2025",
  "python_full_version": "3.13.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.13",
  "sys_platform": "linux"
}
```

### Verbose Command Output

Run `pdm lock -v -G ":all"` fails with:
```
[ProjectError]: Dependency group 'trio' not found
```

### Additional Context

A workaround is to self-declare in the group as follows:
```toml
benchmark-servers-deps = [
    {include-group = "uvloop"},
    "my_project[trio]",
]
```

But it's counter-intuitive.

### Are you willing to submit a PR to fix this bug?

- [ ] Yes, I would like to submit a PR.
