### ISSUE TITLE
Cannot `pdm venv create --with-pip --with uv`

### ISSUE THREAD

**Issue by FedericoStra** [pdm-project/pdm#3495]
### Describe the bug

Creating a virtual environment `--with-pip` and with the `uv` backend fails.

### To reproduce

1. `cd` to a fresh empty directory
2. `pdm venv create --with-pip --with uv`

### Expected Behavior

I expect it to work as it does with `--with-pip` and the other backends (I tested only `venv` and `virtualenv`, not `conda`).

### Environment Information

```yaml
PDM version:
  2.24.1
Python Interpreter:
  /tmp/pdm-venv-pip-uv/.venv/bin/python (3.13)
Project Root:
  /tmp/pdm-venv-pip-uv
Local Packages:

{
  "implementation_name": "cpython",
  "implementation_version": "3.13.3",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.14.2-300.fc42.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Thu Apr 10 21:50:55 UTC 2025",
  "python_full_version": "3.13.3",
  "platform_python_implementation": "CPython",
  "python_version": "3.13",
  "sys_platform": "linux"
}
```

### Verbose Command Output

```console
❯ mkdir /tmp/pdm-venv-pip-uv && cd $_

❯ pdm venv create --with-pip --with uv
INFO: Using uv is experimental and might break due to uv updates.
⠋ Creating virtualenv using uv...error: unexpected argument '/tmp/pdm-venv-pip-uv/.venv' found

Usage: uv venv [OPTIONS] [PATH]

For more information, try '--help'.
[VirtualenvCreateError]: Command '['/home/fstra/.local/bin/uv', 'venv', '-p', '/usr/bin/python',
'--prompt=pdm-venv-pip-uv-3.13', '--seed', 'pip', '/tmp/pdm-venv-pip-uv/.venv']' returned non-zero exit status 2.
```

### Are you willing to submit a PR to fix this bug?

- [x] Yes, I would like to submit a PR.
