### ISSUE TITLE
`pdm export -f pylock ...` produces invalid PEP-751 locks when pdm.lock does not use static URLs.

### ISSUE THREAD

**Issue by jsirois** [pdm-project/pdm#3517]
### Describe the bug

For at least `sdist` and `wheels` `packages` artifacts, if the `pdm.lock` is missing static URLs, then the exported `pylock.toml` will contain `sdist` and `wheels` entries missing both `path` and `url`.

This violates the spec since both an `sdist` and `wheels` must include a `path` or a `url`. The documentation for each of these fields links back up to vcs here:
+ https://packaging.python.org/en/latest/specifications/pylock-toml/#packages-vcs-url
+ https://packaging.python.org/en/latest/specifications/pylock-toml/#packages-vcs-path

Snipped:
```
packages.vcs.url
+ Type: string
+ Required?: if [packages.vcs.path](https://packaging.python.org/en/latest/specifications/pylock-toml/#pylock-packages-vcs-path) is not specified
...

packages.vcs.path
+ Type: string
+ Required?: if [packages.vcs.url](https://packaging.python.org/en/latest/specifications/pylock-toml/#pylock-packages-vcs-url) is not specified
...
```

### To reproduce

```console
# In a pdm repo clone:
:; git checkout 55560dfe852c291b3ecda40795882ab406af59a4

# Using pdm:
:; pdm -V
PDM, version 2.24.1

# Export the `pdm.lock`:
:; pdm export -f pylock -o pylock.toml
```

You'll find entries like this in the exported `pylock.toml`:
```toml
[[packages]]
name = "annotated-types"
version = "0.7.0"
requires-python = ">=3.8"
wheels = [
    {name = "annotated_types-0.7.0-py3-none-any.whl",hashes = {sha256 = "1f02e8b43a8fbbc3f3e0d4f0f4bfc8131bcb4eebe8849b8e5c773f3a1c582a53"}},
]
marker = "\"all\" in extras or \"copier\" in extras or \"template\" in extras"

[packages.sdist]
name = "annotated_types-0.7.0.tar.gz"
hashes = {sha256 = "aff07c09a53a08bc8cfccb9c85b05f1aa9a2a6f23728d790723543408344ce89"}
```

### Expected Behavior

PDM should either fail fast when `pdm.lock` is not created with `-S static_urls` or else do a resolve on-the-fly to fill in those URLs in the exported pylock.

### Environment Information

```console
:; pdm info && pdm info --env
PDM version:
  2.24.1
Python Interpreter:
  /home/jsirois/dev/pdm-project/pdm/.venv/bin/python (3.11)
Project Root:
  /home/jsirois/dev/pdm-project/pdm
Local Packages:
  
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.12",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.14.0-15-generic",
  "platform_system": "Linux",
  "platform_version": "#15-Ubuntu SMP PREEMPT_DYNAMIC Sun Apr  6 15:05:05 UTC 2025",
  "python_full_version": "3.11.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

### Verbose Command Output

Adding `-v` to the export gives no extra output:
```console
:; pdm export -f pylock -o pylock.toml -v
```

### Additional Context

I'm the Pex maintainer and Pex supports both export of PEP-751 locks from its own lock format as well as "installing" (building a PEX) using a `--pylock` lock. The install support was missing extras and dependency-groups support; so I just finished adding that. For my interoperability test I'm using `pdm` since you support exporting `extras`, `dependency-groups` and `default-groups` currently (I had used `uv` for prior interop tests but they do not currently support these features). When using `pdm` for this purpose I hit this issue. I work around by re-generating the `pdm.lock` with `pdm lock --strategy static_urls -L pdm.static-urls.lock`. After that I can export `pdm.static-urls.lock` and everything looks great.

See: https://github.com/pex-tool/pex/pull/2770/files#diff-6cdfb3d08ae66e8e66e0a7500cfb705513a1971b0c47ac17d83765a5a23ccda3R631-R667

### Are you willing to submit a PR to fix this bug?

- [ ] Yes, I would like to submit a PR.
