### ISSUE TITLE
PDM cannot find keyring credentials when not using -v

### ISSUE THREAD

**Issue by canatella** [pdm-project/pdm#523]
- [ X] I have searched the issue tracker and believe that this is not a duplicate.

## Steps to reproduce

I use the python keyring to authenticate to a private pip repo and I try updating a public package.
```
keyring set https://mycompany.jfrog.io/mycompany/api/pypi/mycompany-pip3-stable/simple/ myuser mypassword
keyring set https://mycompany.jfrog.io/mycompany/api/pypi/mycompany-pip3-testing/simple/ myuser mypassword
pdm update conan
[PdmException]: The credentials for https://mycompany.jfrog.io/mycompany/api/pypi/mycompany-pip3-stable/simple/autopep8/ are not provided or correct. Please run the command with `-v` option.
```

If I run the command again with `-v` as suggested, it works correctly.

## Actual behavior

Pdm fails with invalid credentials

## Expected behavior

Pdm does not fail when not using -v

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.6.4                                                   
Python Interpreter: /home/dam/bl/repos/.direnv/python-3.9.5/bin/python (3.9)
Project Root:       /home/dam/bl/repos/bbw                                  
Project Packages:   /home/dam/bl/repos/bbw/__pypackages__/3.9               
{
  "implementation_name": "cpython",
  "implementation_version": "3.9.5",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.11.0-22-generic",
  "platform_system": "Linux",
  "platform_version": "#23-Ubuntu SMP Thu Jun 17 00:34:23 UTC 2021",
  "python_full_version": "3.9.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.9",
  "sys_platform": "linux"
}
```

These are the source added in the `pyproject.toml`
```toml
[tool]
[tool.pdm]
[[tool.pdm.source]]
name = "pypi"
url = "https://mycompany.jfrog.io/mycompany/api/pypi/mycompany-pip3-stable/simple"
verify_ssl = true

[[tool.pdm.source]]
name = "5780b0"
url = "https://mycompany.jfrog.io/mycompany/api/pypi/mycompany-pip3-testing/simple"
verify_ssl = true

[[tool.pdm.source]]
name = "057f20"
url = "https://pypi.python.org/simple/"
verify_ssl = true
```
