### ISSUE TITLE
package py code and dependency to pyz

### ISSUE THREAD

**Issue by qbit-git** [pdm-project/pdm#538]
I noticed [there](https://github.com/pdm-project/pdm/issues/508#issuecomment-863705071) say “ we can publish a single file .pyz so that people can download and run without installing any dependencies”。How do you do that？for example：
`pyproject.toml`
```
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["qbit"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "~2.25.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
`test.py`
```
import requests

def test():
    r = requests.get(r'https://www.httpbin.org/get')
    print(r)

if __name__ == '__main__':
    test()
```
It is best to compile to pyc before packaging ：）

**Comment by frostming** [comment]
You may need [pdm-packer](https://github.com/frostming/pdm-packer).

> It is best to compile to pyc before packaging ：）

It is what `zipapp` does(used in pdm-packer)

**Comment by qbit-git** [comment]
@frostming 
I used pdm-packer，but it cannot work.
``` bash
>>> pdm pack -o test.pyz -m test:test
>>> python3 test.pyz
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "test.pyz\__main__.py", line 3, in <module>
AttributeError: module 'test' has no attribute 'test'
```
`pyproject.toml`
``` toml
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "qbit", email = "qiuhongyang@vipinfo.com.cn"},
]
dependencies = [
    "requests~=2.25",
]
requires-python = ">=3.8"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
```
`test.py`
``` python
import requests

def test():
    r = requests.get(r'https://www.httpbin.org/get')
    print(r)

if __name__ == '__main__':
    test()
```

**Comment by frostming** [comment]
It packs all packages inside `__pypackages__` so the current package must be also injected. You can do this by simply giving a name in pyproject.toml

```toml
[project]
name = "test"
```
