### ISSUE TITLE
[Question] Installing, Scripts Not Being Created

### ISSUE THREAD

**Issue by reskin89** [pdm-project/pdm#549]
I realize I am most likely doing something wrong.

I am on OSX:

```
➜~ pdm --version
pdm, version 1.6.2
```

My pyproject.toml:

```toml
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Ryan Eskin"},
]
dependencies = ["pandas~=1.3", "click~=8.0"]
requires-python = ">=3.9"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""

[project.scripts]
pls = "main:cli"

[project.optional-dependencies]
[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
test = ["pytest~=6.2"]
fmt = ["black~=21.7b0"]
```

running `pdm install` or `pdm install -g` seems to just try to install the dependencies.  `pdm build` builds the egg and such.

I'm purely trying to install my program to my local machine (its a simple click CLI program), but the `pls` console sccript doesn't seem to get setup.

What am I doing wrong here? I've gone through the docs A LOT and can't seem to get this working.
