### ISSUE TITLE
Support multiline string for description

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#646]
## Is your feature request related to a problem? Please describe.

I have a long description (summary) for one of my Python project.
Since TOML supports multiline strings, I wrote it like this:

```toml
[project]
name = "griffe"
version = {use_scm = true}
description = """
Signatures for entire Python programs.
Extract the structure, the frame, the skeleton of your project,
to generate API documentation or find breaking changes in your API.
"""
```

The problem is that the description in PKG-INFO ends up on several lines too, and pypi.org complains that it can't parse it as RST, rejecting the publication of the package.

## Describe the solution you'd like

Ideally, the description would be handled like a doctring: pass it through `inspect.cleandoc` to remove any extra indentation, allowing to start the description directly, without a blank line first.

This would make these OK as well:

```toml
description = """
    Signatures for entire Python programs.
    Extract the structure, the frame, the skeleton of your project,
    to generate API documentation or find breaking changes in your API.
"""
```

```toml
description = """Signatures for entire Python programs.
    Extract the structure, the frame, the skeleton of your project,
    to generate API documentation or find breaking changes in your API."""
```

Maybe strip the ending newline. Also, lines probably need to be concatenated anyway.
So, remove leading/trailing newlines and indentation, and concatenate lines.
