### ISSUE TITLE
Having the --find-links option as in pip

### ISSUE THREAD

**Issue by artuntun** [pdm-project/pdm#739]
Hey folks 👋 

Certain repositories need an extra field to install when using pip. The way you do it is by passing the `-f`. For example 

`pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.9.0+cpu.html`

Is it possible to do this in pdm?

**Comment by frostming** [comment]
In PDM, index url or find links URL is an important information for finding packages, so PDM doesn't provide one-off command line options for them. Instead, specify it in your `pyproject.toml`:

```toml
[[tool.pdm.source]]
url = "https://data.pyg.org/whl/torch-1.9.0+cpu.html"
verify_ssl = true
name = "torch"
type = "find_links"
```
