### ISSUE TITLE
Resolution loop, the return

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#755]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

Follow up of #627.

Here is what happens:

- I test a Copier template by generating a project, entering it, and running `make setup`, which simply calls `pdm install` with multiple Python versions
- I have the `feature.install_cache` feature enabled
- I run the tests a first time: resolution/installing packages works
- I modify the templated pyproject.toml to add a dependency
- I run the tests again, *on the same generated project* (so there's already a pdm.lock): hash mismatch, **resolution loop**
- I remove the `pdm.lock` file and run the tests again: **they pass**
- I remove some deps from the templated pyproject.toml and run tests again (pdm.lock left unchanged): hash mismatch, **resolution loop**
- I manually run `pdm lock`: **it's going to pass** (I know it just by looking at PDM's output as I've ran this *many times* :sweat_smile:)
- I interrupt the `pdm lock` command
- I manually run `pdm install`: hash mismatch, **resolution loop**

The only logical conclusion I can come to, is that `pdm install` with a pyproject.toml that does not match the lock file hash **is not equal** to `pdm lock` + `pdm install`. There seems to be a difference in behavior between what the lock command does, and what the install command does when regenerating the lock file.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.10.3
Python Interpreter: /home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.7.12/bin/python3.7 (3.7)
Project Root:       /media/data/dev/copier-pdm/tests/tmp
Project Packages:   /media/data/dev/copier-pdm/tests/tmp/__pypackages__/3.7
{
  "implementation_name": "cpython",
  "implementation_version": "3.7.12",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.2-arch1-1",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT Fri, 12 Nov 2021 19:22:10 +0000",
  "python_full_version": "3.7.12",
  "platform_python_implementation": "CPython",
  "python_version": "3.7",
  "sys_platform": "linux"
}
```

**Comment by pawamoy** [comment]
You can easily replicate like so:

- create a directory `repro755`
- cd into it
- write this pyproject.toml

```toml
[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[project]
name = "pawamoy-testing"
version = "0.0.0"
description = "Testing this great template"
authors = [{name = "Timothee Mazzucotelli", email = "pawamoy@pm.me"}]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.6.2"
dependencies = []

[tool.pdm]
package-dir = "src"

[tool.pdm.dev-dependencies]
dev = [
    "duty~=0.7",
    "mkdocs-literate-nav~=0.4; python_version >= '3.7'",
    "autoflake~=1.4",
    "flake8-comprehensions~=3.7",
    "flake8-docstrings~=1.6",
    "flake8-string-format~=0.3",
    "flake8-tidy-imports~=4.5",
    "pytest-cov~=3.0",
    "pytest-xdist~=2.4",
]
```
- run `pdm lock`
- manually add a dependency to pyproject.toml, for example `"types-markdown~=3.3"`
- run `pdm install`
