### ISSUE TITLE
self-dependency cannot be resolved

### ISSUE THREAD

**Issue by haoyun** [pdm-project/pdm#775]
```toml
[project]
name = 'my_pkg'

[project.optional-dependencies]
test-utils = ['pytest', 'requests-mock', '...']
test = ['my_pkg[test-utils]']
```

works well with `pip install`, but not with `pdm install`.

Reference:
1. https://github.com/pypa/pip/issues/10393
2. https://discuss.python.org/t/pyproject-toml-optional-dependencies-redundancy-aka-dry-extras/8428
