### ISSUE TITLE
Resolution Loop 3: "Seek and destroy"

### ISSUE THREAD

**Issue by pawamoy** [pdm-project/pdm#781]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

The next chapter of the saga!

Related, resolved issues: #627, #744, #776.

## Steps to reproduce

```toml
[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[project]
name = "ml-project"
description = "ML stuff"
authors = [{name = "someone", email = "someone@hey.com"}]
readme = "README.md"
requires-python = ">=3.6.8"
dynamic = ["version"]
dependencies = [
    "sentence-transformers==2.0.0",
    "torchvision==0.9.1",
    "torch==1.9.1",
    "importlib-metadata>=2.1.0",
]
```

```bash
pdm lock
```

## Actual behavior

Upon locking, PDM will loop on multiple versions of `importlib-metadata`, all the way down to version 2.0.0 or something, and finally print the actual issue:

```
✖ 🔒 Lock failed
Unable to find a resolution for torch==1.9.1 because the following requirements conflict:
  torch==1.8.1 (from <Candidate torchvision 0.9.1 from https://index/simple/torchvision/>)
  torch==1.9.1 (from project)
  torch>=1.6.0 (from <Candidate sentence-transformers 2.0.0 from https://index/simple/sentence-transformers/>)
To fix this, you could try to loosen the dependency version constraintsin pyproject.toml.
See /tmp/pdm-lock-hcodkw1j.log for detailed debug log.
[ResolutionImpossible]: Unable to find a resolution
Add '-v' to see the detailed traceback
```

I believe the packages on which it loops is arbitrary/random (probably just a matter of order). For example, if I add pandas:

```toml
dependencies = [
    "sentence-transformers==2.0.0",
    "torchvision==0.9.1",
    "torch==1.9.1",
    "importlib-metadata>=2.1.0",
    "pandas==1.1.4",
]
```

...PDM will loop on `python-dateutil` instead, this time for real (infinite loop: 2.8.2 to 2.7.3 then back to 2.8.2).

If I reduce the set of dependencies to torch and torchvision (and optionally sentence-transformers), PDM is able to directly print the error shown above.

## Expected behavior

When a compatibility issue is found, don't iterate on irrelevant packages and immediately stop resolution and print the error (this is probably a naive view of the problem/solution).

## Environment Information

```console
% pdm info && pdm info --env
PDM version:        1.11.1
Python Interpreter: /home/user/.basher-packages/pyenv/pyenv/versions/3.8.11/bin/python3 (3.8)
Project Root:       /home/user/data/dev/project
Project Packages:   /home/user/data/dev/project/__pypackages__/3.8
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.11",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "3.10.0-862.6.3.el7.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP Fri Jun 15 17:57:37 EDT 2018",
  "python_full_version": "3.8.11",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```

P.S.: feel free to edit this dumb title to better represent the actual issue 😉
