### ISSUE TITLE
Support resolution overrides

### ISSUE THREAD

**Issue by frostming** [pdm-project/pdm#790]
## Is your feature request related to a problem? Please describe.

PDM should provide a way to override the resolution whether what versions are pinned.

## Describe the solution you'd like
```toml
[tool.pdm]
overrides = {
    click = "8.0.0",
    flask = "2.0.1"
}
```
But if a package won't appear in the final resolution result, it won't be added
