### ISSUE TITLE
Unable to debug tests or code using pdm + vs code

### ISSUE THREAD

**Issue by literallywar** [pdm-project/pdm#975]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

1. pdm init
2. confirm `pdm run <command>` works and includes packages from `__pypackages__`
3. import module installed via `pdm add` into code file
4. navigate to file in vs code
5. press f5 (launch config below may be necessary)

### launch.json
```json
    "configurations": [
        {
            "name": "Python: Example",
            "type": "python",
            "request": "launch",
            "program": "example.py",
            "console": "integratedTerminal"
        }
```

###VS code selected interpreter
![image](https://user-images.githubusercontent.com/84680804/158664229-f69f28eb-96a3-4545-b2b9-8bd89e9bfd57.png)

### .pdm.toml
```toml
[python]
path = "/Users/<user>/.pyenv/versions/3.10.1/bin/python"
```

### pyproject.toml
```toml
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "<name>", email = "<email>"},
]
dependencies = [
    "boto3>=1.21.8",
]
requires-python = ">=3.10"
license = {text = "MIT"}
[project.optional-dependencies]

[tool.pdm.scripts]
start = "python example.py"
test = "pytest"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.0.1",
]
[project.urls]
Homepage = ""
[tool.pdm]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

```

## Actual behavior

error: no module named <module you installed>

## Expected behavior

able to debug code which includes modules installed to `__pypackages__`

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.13.4
Python Interpreter: /Users/<user>/.pyenv/versions/3.10.1/bin/python (3.10)
Project Root:       /Users/<user>/code/learning
Project Packages:   /Users/<user>/code/learning/__pypackages__/3.10
{
  "implementation_name": "cpython",
  "implementation_version": "3.10.1",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "21.3.0",
  "platform_system": "Darwin",
  "platform_version": "Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101",
  "python_full_version": "3.10.1",
  "platform_python_implementation": "CPython",
  "python_version": "3.10",
  "sys_platform": "darwin"
}
```

### .vscode/settings.json
```json
{
    "python.autoComplete.extraPaths": [
        "${workspaceFolder}/__pypackages__/3.10/lib"
    ],
    "python.analysis.extraPaths": [
        "${workspaceFolder}/__pypackages__/3.10/lib"
    ],
    "python.testing.pytestArgs": [
        "."
    ],
    "python.testing.unittestEnabled": false,
    "python.testing.pytestEnabled": true,
    // I've tried:
    // ${workspaceFolder}/__pypackages__/3.10/bin/pytest
    // ./__pypackages__/3.10/bin/pytest
    // __pypackages__/3.10/bin/pytest
    "python.testing.pytestPath": "${workspaceFolder}/__pypackages__/3.10/bin/pytest"
}
```

**Comment by literallywar** [comment]
FIXED debugging by adding the below to vs code launch configurations - my only remaining issue is that vscode's pytest extension does not see pytest (no module named 'pytest' found)

```json
  "env": {
      "PYTHONPATH": "__pypackages__/3.10/lib"
  }
```

**Comment by Itay4** [comment]
@literallywar did you figure this out ?

**Comment by rami3l** [comment]
A note for myself: what @literally-luck proposed can also be achieved with creating an `.env` file. See: https://github.com/pdm-project/pdm/issues/848#issuecomment-1032696178.

**Comment by literally-luck** [comment]
Hey all, I literally just this moment got everything working

![image](https://user-images.githubusercontent.com/84680804/166728677-8c59079c-5f96-488d-8dd9-af2b744868c1.png)

I'll list out my setup with everything I can think of - but there's one final thing that made it all work.. Deleting all *_cache files and __pypackages__, then reinstalling - everything works now, and it is super cool.

## settings.json
```json
{
    "python.autoComplete.extraPaths": [
        "${workspaceFolder}/__pypackages__/3.10/lib"
    ],
    "python.analysis.extraPaths": [
        "${workspaceFolder}/__pypackages__/3.10/lib"
    ],
    "python.testing.pytestArgs": [
        "."
    ],
    "python.testing.unittestEnabled": false,
    "python.testing.pytestEnabled": true,
    "python.testing.pytestPath": "${workspaceFolder}/__pypackages__/3.10/bin/pytest",
    "terminal.integrated.env.osx": {
        "PYTHONPATH": "${workspaceFolder}/__pypackages__/3.10/lib"
    },
}
```

## Using vs code recommended python interpreter
![image](https://user-images.githubusercontent.com/84680804/166729026-dac71ea7-b2b6-4028-8584-f5fb99e42106.png)

## Same in .pdm.toml
```toml
[python]
path = "~/.pyenv/versions/3.10.1/bin/python"
```

I've tried this and other formats, but it was this combination + hard deleting/reinstalling that kicked it into a working state. I hope this helps!
