### ISSUE TITLE
`pdm add <package>` appends commas to `pyproject.toml` comments

### ISSUE THREAD

**Issue by dranjan** [pdm-project/pdm#994]
- [x] I have searched the issue tracker and believe that this is not a duplicate.

**Make sure you run commands with `-v` flag before pasting the output.**

## Steps to reproduce

Start with this `pyproject.toml`:
```toml
[project]
name = "test_project"
version = "0.0"
description = "test project"
authors = [
]
dependencies = [
    # Here's a comment.
    "numpy~=1.22",
]
requires-python = ">=3.8"
license = {text = ""}

[project.urls]
homepage = ""

[tool]
[tool.pdm]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
```

Then add a package, e.g., `pdm add pybind11==2.4.3`.

## Actual behavior

The package appears to be added correctly, but the "Here's a comment" comment gets corrupted:

```diff
diff --git a/test_project/pyproject.toml b/test_project/pyproject.toml
index de83578..f432178 100644
--- a/test_project/pyproject.toml
+++ b/test_project/pyproject.toml
@@ -5,8 +5,9 @@ description = "test project"
 authors = [
 ]
 dependencies = [
-    # Here's a comment.
+    # Here's a comment.,
     "numpy~=1.22",
+    "pybind11==2.4.3",
 ]
 requires-python = ">=3.8"
 license = {text = ""}
```

Calling `pdm add` multiple times will keep appending commas onto that comment.

## Expected behavior

The package is added, but comments are unaffected.

## Environment Information

```bash
# Paste the output of `pdm info && pdm info --env` below:
PDM version:        1.13.5
Python Interpreter: /tmp/venv/bin/python (3.8)
Project Root:       /tmp/test_project
Project Packages:   /tmp/test_project/__pypackages__/3.8
{
  "implementation_name": "cpython",
  "implementation_version": "3.8.10",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.4.0-104-generic",
  "platform_system": "Linux",
  "platform_version": "#118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022",
  "python_full_version": "3.8.10",
  "platform_python_implementation": "CPython",
  "python_version": "3.8",
  "sys_platform": "linux"
}
```
